### ISSUE TITLE
KeyError Exception: key not found: "storage"

### ISSUE THREAD

**Issue by ricardopacheco** [janko-m/shrine#103]
API (cURL):

```
curl -X POST -H "uid: user@provider.com" -H "access-token: ITP_S19rXuET0KZXRDZmrQ" -H "expiry: 1478796120" -H "client: kBC8uTUEAwzOifYCmUm8-g" -H "token-type: Bearer" -H "Content-Type: multipart/form-data;" -H "Cache-Control: no-cache" -F "shipping[file]=@/Users/users/documents/remessa.csv" "http://api.local.dev:3000/v1/shippings"
```
Log:

```
Processing by Api::V1::ShippingsController#create as CSV
  Parameters: {"shipping"=>{"file"=>#<ActionDispatch::Http::UploadedFile:0x0055898c70f740 @tempfile=#<Tempfile:/tmp/RackMultipart20161103-1-1xrmcts.csv>, @original_filename="remessa.csv", @content_type="application/octet-stream", @headers="Content-Disposition: form-data; name=\"shipping[file]\"; filename=\"remessa.csv\"\r\nContent-Type: application/octet-stream\r\n">}, "subdomain"=>"api"}
  User Load (4.4ms)  SELECT  "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2  [["uid", "email@provider.com"], ["LIMIT", 1]]

[2, 11] in /usr/src/app/app/controllers/api/v1/shippings_controller.rb
    2:   class ShippingsController < ApplicationController
    3:     before_action :authenticate_user!
    4:
    5:     def create
    6:       byebug
=>  7:       @import = ShippingOccurrenceImport.import!(params[:shipping][:file])
    8:       render json: { "message": @import }, status: 200
    9:     end
   10:
   11:     def edit
(byebug) @import = ShippingOccurrenceImport.import!(params[:shipping][:file])
STORE[cache] FileUploader[:file] Shipping 1 file (0.02s)
*** KeyError Exception: key not found: "storage"

nil
(byebug)
```

```
require 'shrine'
require 'shrine/storage/file_system'
require 'image_processing/mini_magick'

Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new('public', prefix: 'uploads/cache'),
  store: Shrine::Storage::FileSystem.new('public', prefix: 'uploads/store')
}

Shrine.plugin :activerecord
Shrine.plugin :cached_attachment_data
Shrine.plugin :determine_mime_type
Shrine.plugin :direct_upload, max_size: 10*1024*1024 # 10 MB
Shrine.plugin :parsed_json
Shrine.plugin :rack_file
Shrine.plugin :logging, logger: Rails.logger
```

```
class FileUploader < Shrine
  def process(io, context)
    case context[:phase]
    when :store
      file = io.download

      { file: file }
    end
  end
end
```

```
class Shipping < ApplicationRecord
  include FileUploader[:file]
end
```

```
class CreateShippings < ActiveRecord::Migration[5.0]
  def change
    create_table :shippings do |t|
      t.json :file_data, null: false, default: '{}'

      t.timestamps
    end
  end
end
```

Shrine: 4.2.1
Ruby: 2.3.1
Rails: 5.0.0.1

**Comment by janko-m** [comment]
The issue is that you're setting the default of `file_data` column value to be `{}`. However, Shrine relies on that when an attachment is missing, the column value returns `nil`. If the column returns a hash, then Shrine thinks it's a serialized uploaded file and attempts to instantiate a `Shrine::UploadedFile` object, which asserts that the `storage` JSON key is present. Since an empty hash doesn't contain this key, Shrine fails.

The solution is to just create a JSON column without a default value:

```rb
class CreateShippings < ActiveRecord::Migration[5.0]
  def change
    create_table :shippings do |t|
      t.json :file_data

      t.timestamps
    end
  end
end
```

**Comment by janko-m** [comment]
I also want to mention few notes, unrelated to this issue:

I noticed that you want to save a hash of versions, just note that for that you need to load the `versions` plugin. And also you can avoid an additional copy in processing by not downloading the cached file and passing it directly instead:

```rb
class FileUploader < Shrine
  def process(io, context)
    case context[:phase]
    when :store
      { file: io }
    end
  end
end
```

Also, it's recommended to either use the `processing` plugin, or switch from `context[:phase]` to `context[:action]`, as in Shrine 3 `context[:phase]` won't work anymore.

Another tiny note is that you don't need the `rack_file` plugin in Rails apps, since Rails converts Rack uploaded file hash into `ActionDispatch::Http::UploadedFile`, which is already an IO-like object that Shrine can upload.

**Comment by ricardopacheco** [comment]
@janko-m not working! `Shrine cannot upload the same IO object multiple times`

```
    when :store
      file = io.download

      large      = resize_to_limit!(file, 400, 250)
      thumbnail  = resize_to_limit!(file, 50, 50)

      { large: large, thumbnail: thumbnail }
    end
```

**Comment by janko-m** [comment]
@ricardopacheco This error says that `:large` and `:thumbnail` versions are the same IO object (file). This happened because you didn't generate a new thumbnail from the large version, you modified the file in-place (using the "bang" version), so now both `large` and `thumbnail` point to the `50x50` version. In the second line you have to use the non-bang processing method, to create a new image:

```
    when :store
      file = io.download

      large      = resize_to_limit!(file, 400, 250)
      thumbnail  = resize_to_limit(file, 50, 50) # using the non-bang version creates a new image

      { large: large, thumbnail: thumbnail }
    end
```

**Comment by janko-m** [comment]
@ricardopacheco Also, notice that what's not working for you is a complete separate issue than your original issue, so you should open a separate ticket for that in the future, or better yet report it on the Shrine Google group if you're not sure whether it's a bug with Shrine.
