### ISSUE TITLE
Image cropping?

### ISSUE THREAD

**Issue by activestylus** [janko-m/shrine#106]
I know I can to stuff like this:

```ruby
size_1280 = resize_to_limit!(original, 1280, 1280)
size_900  = resize_to_limit(size_1280,  900, 1280)
```

But all that does is shrink the image to fit those dimensions. How can I make it so that shrine can create a cropped, square thumbnail?

**Comment by activestylus** [comment]
This is what I needed: https://github.com/janko-m/image_processing

**Comment by activestylus** [comment]
OK got a little ahead of myself when I closed this. Still no joy :/

When I try to upload. this is what happens:

**IOError: closed stream**

What am I missing?

```ruby
require "image_processing/mini_magick"

class ImageUploader < Shrine
  include ImageProcessing::MiniMagick
  opts[:type] = "image"
  plugin :processing
  plugin :versions
  plugin :store_dimensions

  process(:store) do |io, context|
    original  = io.download
    size_1280 = resize_to_limit!(original, 1280, 1280)
    size_900  = resize_to_limit(size_1280,  900, 1280)
    size_400  = resize_to_limit(size_900,  400, 800)
    
    thumb = with_minimagick(size_400) do |img|
      img.combine_options do |cmd|
        cmd.resize '150x150!'
      end
    end  

    { original: io, large:  size_1280, medium: size_900, small:  size_400, thumb: thumb }
  end

end
```

**Comment by activestylus** [comment]
I should also add that I tried:

```
thumb = crop(size_400, 150, 150, 0, 0, gravity: "NorthWest")
```

There are no errors when I do this, but the file is simply resized, not cropped.

When I try it like this with `crop!`

```
thumb = crop!(size_400, 150, 150, 0, 0, gravity: "NorthWest")
```

I get that pesky IO error - I guess the ! is what opens up the stream, thats why you cant do it twice?

**Comment by janko-m** [comment]
An `IOError: closed stream` error is raised when you try to do something with a file that was already closed. It's strange that you're getting this error, could you include a backtrace, so that we know on which line it is happening?

**Comment by janko-m** [comment]
@activestylus Ok, I managed to reproduce the bug. So, the reason for this error is that `with_minimagick` doesn't make a copy of the image, and neither does `MiniMagick::Image#combine_options`. This means that when you're generating a thumbnail, you're actually modifying the image in place.

So then you have two images which are the same Ruby object (`size_400` and `thumb`). Now, whenever Shrine uploads a file, it first extracts metadata from it, and after uploading it closes the file. This means that once `size_400` gets uploaded and closed, `thumb` will also get closed because they are the same `Tempfile` object. Then when Shrine attempts to extract dimensions from `thumb`, it errors when it attempts to read from it, since the file is already closed. This is why `crop!` fails as well, because it processes the image in-place.

The simplest way to handle this is to make a copy of `size_400` before passing it to `with_minimagick`, which is what the other image_processing methods are doing under the hood as well.

```rb
    thumb = with_minimagick(_copy_to_tempfile(size_400)) do |img|
      img.combine_options do |cmd|
        cmd.resize '150x150!'
      end
    end  
```

However, I noticed that `150x150!` squeezes the image into the squared dimensions, instead of maintaining aspect ratio. Furthermore, when I try using `crop`, for me it does in fact crop the image (although the quality sucks), so I suggest using that. If you believe `crop` is not working properly, do open an issue on the image_processing repository with an example image which doesn't crop correctly.

**Comment by activestylus** [comment]
Thanks for the prompt and informative reply @janko-m. Makes sense and I just confirmed that it works/

BTW, I haven't seen such a tidy/thorough issues section (0 open!) since Jeremy Evans. Bravo for that - you're in good company there

**Comment by janko-m** [comment]
@activestylus Thank you! Jeremy Evans has been (and continues to be) a huge inspiration to me, I'm just trying to maintain Shrine like he would 😃

**Comment by musaffa** [comment]
@janko-m `_copy_to_tempfile` isn't available in the recent `image_processing` release. Is there any public API similar to `_copy_to_tempfile`?

**Comment by janko-m** [comment]
Shrine 2.11+ added the `Shrine.with_file` method that acts like `_copy_to_tempfile`, though it has slightly different behaviour. While `_copy_to_tempfile` always copies the given IO object into a new Tempfile, `Shrine.with_file` will

* yield the IO object if it's a `File`/`Tempfile` object
* call `#download` if it's a `Shrine::UploadedFile` object
* copy contents to a new Tempfile otherwise

`Shrine.with_file` also accepts a mandatory block, and the Tempfile is deleted at the end of the block.

```rb
file #=> an object that responds to #path
Shrine.with_file(file) do |file|
  file # the same File object
end

uploaded_file #=> a Shrine::UploadedFile object
Shrine.with_file(uploaded_file) do |file|
  file # a tempfile created from #download
end

io #=> generic IO-like object that responds to #read
Shrine.with_file(io) do |file|
  file # a new tempfile with copied content 
end
```

Would that work for you?

**Comment by hmistry** [comment]
@musaffa Next time please ask on the Shrine google group or open a new issue as per our guidelines. Hijacking other issues with somewhat unrelated questions makes it harder for us to track frequencies of issues and prevents others from finding the solution when they look for past issues that have a similar problem they are encountering. Thank you for your cooperation.
