### ISSUE TITLE
Shrine finalize or promote bug

### ISSUE THREAD

**Issue by vladra** [janko-m/shrine#109]
Hi :v:

Im trying to setup shrine with ROM, and using this repo as an example of implementation https://github.com/janko-m/shrine-rom-example

And I've encountered an error. My logs look like this:
```
STORE[cache] Uploaders::ImportPrice[:file] Entities::Supplier[12] 1 file (0.01s)
STORE[store] Uploaders::ImportPrice[:file] Entities::Supplier[12] 1 file (0.04s)
DELETE[abort] Uploaders::ImportPrice[:file] Entities::Supplier[12] 1 file (0.0s)
```

So, first, file is assigned to cache storage. Then, when trying to finalize, it saves record to store storage, but immediately deletes it afterwards. If I understood correctly, it is happening on this line of code:
https://github.com/janko-m/shrine/blob/master/lib/shrine.rb#L545
```ruby
        def promote(uploaded_file = get, **options)
          stored_file = store!(uploaded_file, **options)
          result = swap(stored_file) or _delete(stored_file, action: :abort)
          result
        end
```

Shouldn't it delete `uploaded_file` instead of `stored_file`?

So currently, I have a bug and can't save file to `store` storage.

My Shrine version is 2.5.0.

**Comment by janko-m** [comment]
@vladra Hey, sorry for responding only now, it was a bit busy at work.

So, Shrine will "abort" promoting (by [deleting the promoted file](https://github.com/janko-m/shrine/blob/90b9a4ed301ff778a6b65b51766ff058fca915c9/lib/shrine.rb#L545)), when it detects that updating the record with the promoted file failed. And it does so if `Attacher#swap` returns `false`.

A promotion "failing" is normally related only to backgrounding. Since a background job is asynchronous, it can happen that someone changes the attachment on the record, or the record gets deleted, before the processing and reuploading is finished. In that case, Shrine knows that it shouldn't try to update the record with promoted files, and then it also deletes the promoted files since they won't be attached anywhere ([code](https://github.com/janko-m/shrine/blob/90b9a4ed301ff778a6b65b51766ff058fca915c9/lib/shrine/plugins/backgrounding.rb#L247-L248)).

In addition to that, to give ORM plugins the ability to implement atomic updates (see description of https://github.com/janko-m/shrine/commit/5d7cab67b65807ecbb56e5552871ffed5da34726), after the record has been updated with the new attachment, Shrine also checks whether the attachment was successfully updated, and returns this as the returned value of `Attacher#swap` ([code](https://github.com/janko-m/shrine/blob/90b9a4ed301ff778a6b65b51766ff058fca915c9/lib/shrine.rb#L553)).

So, when promoting aborts, it's because [this](https://github.com/janko-m/shrine/blob/90b9a4ed301ff778a6b65b51766ff058fca915c9/lib/shrine/plugins/backgrounding.rb#L247-L248) or [this](https://github.com/janko-m/shrine/blob/90b9a4ed301ff778a6b65b51766ff058fca915c9/lib/shrine.rb#L553) check returned false. I'm suspecting it's the latter, although I'm not sure how it happens, because the ROM plugin from shrine-rom-example [updates the record with the result of repository update](https://github.com/janko-m/shrine-rom-example/blob/master/config/shrine-rom.rb#L25) (which *should* be the updated model instance).

**Comment by vladra** [comment]
@janko-m Thank you very much for clarification

**Comment by janko-m** [comment]
@vladra Did you manage to determine why this was happening? Does this happen when you just clone shrine-rom-example and run it?

**Comment by vladra** [comment]
@janko-m it was happening with my custom implementation (not with shrine-rom-example). I've configured it a little differently afterwards (I don't need to save file info to DB), so I can't say for sure why it was happening.
