### ISSUE TITLE
Receiving cached attachment data in Capybara tests

### ISSUE THREAD

**Issue by ollieh-m** [janko-m/shrine#120]
Capybara tests do not receive the value supplied in the hidden field containing cached attachment data. 

This is only where that hidden field has the same name as the real input field - as required in the deprecation warning against giving the hidden field a different name. When the field has a different name, its value is received in the request params.

Chrome submits the hidden value without a problem, so I assume this is a Capybara/webkit issue, but it's also a problem if Shrine no longer supports giving the hidden field a different name. 

(I have managed to get my tests working by using a different name for the field, but this raises other complexities around when to used values from either field and mapping the hidden field's value onto the correct attribute for the model.)

**Comment by janko-m** [comment]
If by Shrine raising a deprecation warning for hidden field with different name you were referring to the deprecation of `cached_<attachment>_data` writer, the reason for that was explained in https://github.com/janko-m/shrine/commit/0cf395b65d23c0cb89dea5368b86ce14f024f650. TL;DR it caused hard-to-debug issues around validations when the order of parameters would accidentally be reversed with strong_parameters. I don't think this writer should be brought back.

If `capybara-webkit` doesn't support this functionality, that in case file field doesn't have a file attached it isn't submitted to the app (and instead falls back to the hidden field), then it's a bug in `capybara-webkit`, because that's the behaviour of all browsers.

So this issue should be fixed in `capybara-webkit`, or alternatively you could use PhantomJS or Selenium (in headless mode) with Capybara.
