### ISSUE TITLE
error in everything

### ISSUE THREAD

**Issue by armanlearn** [janko-m/shrine#123]
hi ,
I create image_data:text filed as shrine guides. mount image uploader, create shrin rb and set filesystem storage.
file upload and dont go in public , they go to /tmp
when i want to show error happend and said:
784: unexpected token at '#<ActionDispatch::Http::UploadedFile:0x000000038dd580>'

in consol i write
@book.image_url
and get this error
JSON::ParserError: 784: unexpected token at '#<ActionDispatch::Http::UploadedFile:0x000000038dd580>'

------- 
as articles i read shrine is new and best solution but lack of tutorial.

tanks

**Comment by janko-m** [comment]
@armanlearn Are you sure you did exactly as in the "quick start" section in the README? It seems that you've ended up with `#ActionDispatch::Http::UploadedFile:0x000000038dd580` assigned to your `image_data` column as a *string*. That's why the JSON parsing is failing, because it tries to parse that string as JSON.

You probably create a form field for `image_data` instead of `image`. You cannot assign files to the `image_data` column, because it's a text column, it's what Shrine uses internally to store the uploaded file data. You need to use Shrine's `image` virtual attribute that was added to your model by Shrine's attachment module. That is documented in the "quick start" section of the README.

Note that as per contribution guidelines, if you're not sure that something is a bug, it's better to first report it to the Shrine google group.
