### ISSUE TITLE
validation_helpers doesn't get the mime_type

### ISSUE THREAD

**Issue by R4ttlesnake** [janko-m/shrine#133]
Hi,
I'm using the validation_helpers plugin to validate the size and mime-type of my upload. Running a model spec without the mime-type validation, the spec passes. With the mime-type validation and any image-file I try, the validation fails. 

Checking the mime type of the test-file in my terminal says _image/jpeg_. I tried checking the mime-type with `puts get.mime_type` in the Attacher block, but it only returns an empty line in the terminal.

Do you know how to solve this (below my code)?

Thanks

ps: There is a typo on the [validation_helpers docs](http://shrinerb.com/rdoc/classes/Shrine/Plugins/ValidationHelpers.html). In the first code block it says _validat_mime_type_inclusion_, it should probably be _validate_mime_type_inclusion_.

uploaders/image_uploader:
```
Attacher.validate do
  puts get.mime_type # returns empty strings
  validate_mime_type_inclusion %w[image/jpeg image/png image/gif]
  validate_max_size 4.megabyte, message: "your file is too large (max. 4MB)"
end
```

initializers/shrine.rb:
```
require 'shrine'
require 'shrine/storage/file_system'
require 'shrine/storage/memory'

if Rails.env.test?
  Shrine.storages = {
    cache: Shrine::Storage::Memory.new,
    store: Shrine::Storage::Memory.new,
  }
else
  Shrine.storages = {
    cache: Shrine::Storage::FileSystem.new('public', prefix: 'uploads/cache'),
    store: Shrine::Storage::FileSystem.new('public', prefix: 'uploads/store'),
  }
end

Shrine.plugin :activerecord
Shrine.plugin :cached_attachment_data
Shrine.plugin :logging, logger: Rails.logger
```

spec:
```
# valid without validate_mime_type_inclusion
# invalid with validate_mime_type_inclusion
exhibition.image = File.open(File.join(Rails.root, 'spec/support/test_files/haruki.jpg'))
expect(exhibition).to be_valid
```

**Comment by janko-m** [comment]
Could you also post your uploader code? The metadata extraction is a separate process from validations, the `validation_helpers` doesn't affect the MIME type extracted in any way, it just provides helper methods for validating the values that were already extracted.

Note that by default Shrine will only populate the `mime_type` metadata if the given file responds to `#content_type`. The `ActionDispatch::Http::UploadedFile` in the Rails controller (or file assigned by the `rack_file` plugin) responds to `#content_type`, populated from the `Content-Type` request header, so Shrine simply copies that value over as `mime_type`.

Shrine won't automatically try to determine the MIME type from extension or file contents, because it doesn't know which library you would like to use (`mime-types`, `file` utility, `mimemagic`, `ruby-filemagic`, or something else). In order to extract the actual MIME type from any IO object you need load the `determine_mime_type` plugin.

```
plugin :determine_mime_type
```

**Comment by R4ttlesnake** [comment]
I added the `:determine_mime_type` plugin and with this Shrine gets the file's MIME type and `validate_mime_type_inclusion` works properly. Thanks!

For your information, there is still the typo in the [validation_helpers docs](http://shrinerb.com/rdoc/classes/Shrine/Plugins/ValidationHelpers.html), mentioned in my first comment. Below my working uploader code:

```
require 'image_processing/mini_magick'
require 'fastimage'

class ImageUploader < Shrine
  include ImageProcessing::MiniMagick

  plugin :store_dimensions
  plugin :processing
  plugin :versions
  plugin :determine_mime_type
  plugin :validation_helpers
  plugin :delete_raw

  Attacher.validate do
    # validation works now with the :determine_mime_type plugin
    puts get.mime_type
    validate_mime_type_inclusion %w[image/jpeg image/png image/gif]
    validate_max_size 4.megabyte, message: "your image is too large (max. 4MB)"
  end

  process(:store) do |io|
    # process
    original = auto_orient!(io.download)
    full = resize_to_limit(original, 3500, 2500)
    thumb = resize_to_limit(full, 400, 400)

    # crop
    width = FastImage.size(original)[0]
    height = FastImage.size(original)[1]

    if width >= height
      postcard = resize_to_fill(full, 1748, 1240, gravity: "Center")
    else
      postcard = resize_to_fill(full, 1240, 1748, gravity: "Center")
    end

    # versions
    { full: full, thumb: thumb, postcard: postcard }
  end
end
```

**Comment by janko-m** [comment]
@R4ttlesnake Great that it worked. The typo was fixed on master, but I still haven't published the updated documentation to the website. I will get to it as soon as I slow down my crazy rhythm of traveling across Australia 😛
