### ISSUE TITLE
Sending file in queue with Sidekiq

### ISSUE THREAD

**Issue by brunowego** [janko-m/shrine#137]
I'm trying to solve this problem, I do not want to bother you, maybe you can answer.

When submitting a remittance, I receive this warning on Sidekiq:

```
Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/Bruno/Workspace/secret.com/platform/api/public/uploads/store/remittance/file/f1b1a41dd520fcca265d43b6adc5df0c.csv
```

I believe the file has not yet been uploaded, I'm trying to access the store instead of caching. Take a loot at my code:

```rb
class Remittance < ApplicationRecord
  ...
  after_commit -> { RemittanceProcessJob.perform_later self }, on: :create
  ...
end
```

```rb
class RemittanceProcessJob < ApplicationJob
  queue_as :default

  def perform(remittance)
    ...
    Remittance::ImportService.new(remittance).csv
    ...
  end
end
```

```rb
class Remittance::ImportService
  ...
  def file_path
    store_path = "#{Rails.root}/public/uploads/store"
    File.open(File.join(store_path, @remittance.file.id))
  end
  ...
end
```

Many thanks for your patience and time.

**Comment by brunowego** [comment]
That way it works, if you have any tips for a better way, I'll be very grateful!

```rb
class Remittance::ImportService
  def csv
    CSV.parse(@remittance.file.read, headers: true) do |row|
      user(row).add_role :guest, dispute(row)
    end
  end
end
```

**Comment by janko-m** [comment]
Again, you should never read the whole file into memory (by calling `#read` with no arguments on the IO) 😉. You can have the CSV library parse the file line by line by giving a real IO object (e.g. `File`, `Tempfile`, or `StringIO`) to `CSV.new`.

If you want to be storage-agnostic (that it works regardless of the storage that you're using), you can `#download` the uploaded file in order to obtain a `Tempfile` object, and give it to `CSV.new`.

```rb
class Remittance::ImportService
  def csv
    tempfile = @remittance.file.download
    csv = CSV.new(tempfile, headers: true)
    csv.each do |row|
      user(row).add_role :guest, dispute(row)
    end
    tempfile.close! # close and delete the temporary file
  end
end
```

If on the other hand you know that your storage is `Shrine::Storage::FileSystem` and you don't expect it to change, you can use the fact that this storage internally uses a real `File` object, and avoid the extra copy by using `#open`.

```rb
class Remittance::ImportService
  def csv
    @remittance.file.open do |file|
      csv = CSV.new(file, headers: true)
      csv.each do |row|
        user(row).add_role :guest, dispute(row)
      end
    end
  end
end
```

Note that, as per contribution guidelines, questions should be asked on the Shrine Google group, and GitHub issues should be used only for bug reports 😉
