### ISSUE TITLE
"Shrine cannot upload the same IO object multiple times" when avoiding processing in testing environment

### ISSUE THREAD

**Issue by R4ttlesnake** [janko-m/shrine#138]
Hi, I want to avoid processing in my request specs with Shrine uploads. According to the [Testing with Shrine docs](http://shrinerb.com/rdoc/files/doc/testing_md.html), I tried these two ways in my _image_uploader.rb_:

```
if Rails.env.test?
  def process(io, context)
    if context[:action] == :store
      { full: io, thumb: io, postcard: io }
    end
  end
end
```

and

```
if Rails.env.test?
  process(:store) do |io|
    { full: io, thumb: io, postcard: io }
  end
end
```

In both cases I get the error message: _"Shrine cannot upload the same IO object multiple times."_ Another solution would be to not process at all in the test environment, but this will throw me other test errors, as my views are looking for a non-existent `image[:thumb].url`. How can I avoid the processing and keep the versions intact while testing?

**Comment by janko-m** [comment]
@R4ttlesnake Oh, right, I have't thought actually tested this out when writing the docs 😞. The reason why Shrine cannot upload the same IO object multiple times is because it closes each object after upload, so since versions are uploaded synchronously the second upload would fail with a `IOError: closed stream`.

I *think* it should work if you `#dup` the `Shrine::UploadedFile` object in other versions:

```rb
if Rails.env.test?
  def process(io, context)
    if context[:action] == :store
      { full: io, thumb: io.dup, postcard: io.dup }
    end
  end
end
```

Note that we need to actually `def process` in order to override it, calling `process { ... }` would add another step *in addition to* what is already defined.

**Comment by R4ttlesnake** [comment]
I tried your code to duplicate the io via `.dup` in test environment, but I still get the same error when my app tries to save the record:

_Shrine::Error: The following version keys point to the same IO object: [:full, :thumb, :postcard]. Shrine cannot upload the same IO object multiple times._

An example request spec for my create method:

```
# attributes to post to create path
exhibition_attr = attributes_for(:exhibition)
exhibition_attr[:image] = Rack::Test::UploadedFile.new(File.join(Rails.root, 'spec/support/test_files/haruki.jpg'))

# expectation
expect { post exhibitions_path, params: { exhibition: exhibition_attr } }.to change(Exhibition, :count).by(1)
```

Any other suggestions how to avoid the processing in testing? Thanks.

**Comment by janko-m** [comment]
Oh, I think I know why it's still failing. I original thought that this code is comparing `#object_id` of each IO, but it's actually using regular equality (`#==`). Since `Shrine::UploadedFile` overrides `#==` to match the data hash, `io` will equal `io.dup`, because they have the same data hash.

What *should* definitely work is if you download the `Shrine::UploadedFile` object denoted by the `io` variable for each version, since that will literally create separate copies of the file.

```rb
if Rails.env.test?
  def process(io, context)
    if context[:action] == :store
      { full: io, thumb: io.download, postcard: io.download }
    end
  end
end
```

**Comment by R4ttlesnake** [comment]
Yes, the `io.download` instead of reusing the `io` will do the trick. Thanks!

One question: what does the .download actually do in comparsion of using io directly?

**Comment by janko-m** [comment]
The `io` object always holds the file being uploaded. When caching, it will hold the file that was assigned (in a Rails controller that's an ActionDispatch::Http::UploadedFile object).

When promoting, the `io` will be a Shrine::UploadedFile object representing the cached file on temporary storage. If you're doing direct uploads to S3, this object would represent a file on S3 (it's just an object containing the information where the file is uploaded).

Now, when promoting, why doesn't Shrine just automatically download the cached file from the temporary storage before processing? Well, because if both od your temporary and permanent storage is S3, then if you want to upload the original cached file as one of the versions, Shrine can simply issue an S3 copy request, thus avoiding needing to reupload the file to permanent storage (for that it uses the information stored on the Shrine::UploadedFile object). That's why it's generally more performant to assign the Shrine::UploadedFile object as one of the versions if you want to keep the original.

The `#download` method downloads the file to disk, and returns a Tempfile object. Now, your temporary storage may already be FileSystem (which is disk), but you still want to be working with copies, so that's why the `#download` abstraction.

**Comment by R4ttlesnake** [comment]
Thanks for the help so far and avoiding the processing still works well as described.

I ran into a new problem regarding the `io` and `io.download` and as it is still regarding the UploadedFile object, I thought it is better to reopen this existing issue.

Following the [Custom Processing section of Shrine's GitHub page](https://github.com/janko-m/shrine#custom-processing), I was building a _VideoUploader_:

```
require "image_processing/mini_magick"
require "streamio-ffmpeg"

class VideoUploader < BaseUploader
  include ImageProcessing::MiniMagick

  plugin :processing
  plugin :versions

  # validate videos
  Attacher.validate do
    # validations…
  end

  # process / versions
  process(:store) do |io, context|

    original = io.download

    video = Tempfile.new(["video", ".mp4"], binmode: true) 
    still = Tempfile.new(["still", ".jpg"], binmode: true)

    movie = FFMPEG::Movie.new(original.path)
    movie.transcode(video.path)
    movie.screenshot(still.path)

    { video: video, still: still }
  end
end
```

I'm testing this _VideoUploader_ in my Rails console like this…

```
file = File.open(File.join(Rails.root, "path/to/file.mkv"))
uploader = VideoUploader.new(:store)
```

…and I get a _NoMethodError: undefined method 'download' for #<File:0x007f95b35b7b38>_. If I use the `io` instead of `io.download`, everything works well. Why doesn't `.download` work in this case?

Thanks.

**Comment by janko-m** [comment]
@R4ttlesnake When using the Shrine::Attacher in a regular attachment flow, on "promotion" Shrine will upload the cached `Shrine::UploadedFile` to permanent storage, and this is the object that will get passed to the processing as `io`. This object responds to `#download`.

However, in your case you triggering uploading to permanent storage directly using raw a `File` object, so that will be passed as the `io` argument now, and `File` objects don't respond to `#download`.

In order to test the processing in isolation, you should first upload the raw file to temporary storage, and then pass it for uploading to permanent storage.

```rb
file = File.open(File.join(Rails.root, "path/to/file.mkv"))

cache_uploader = VideoUploader.new(:cache)
cached_file = cache_uploader.upload(file, action: :cache)

store_uploader = VideoUploader.new(:store)
result = store_uploader.upload(cached_file, action: :store)
```

Note that as per contribution guidelines, if you're not sure whether something is a bug, it's best to first ask about it on the Shrine Google group.

**Comment by R4ttlesnake** [comment]
Thanks, that made it clear.
(And sorry about reopening this issue, I'll consult the Google Group next time.)
