### ISSUE TITLE
Using DownloadEndpoint produces an error in routes

### ISSUE THREAD

**Issue by bodrovis** [janko-m/shrine#145]
Hello! I am using this plugin http://shrinerb.com/rdoc/classes/Shrine/Plugins/DownloadEndpoint.html for download endpoints but can't get it to work. I've added `roda` into my gemfile, added

```ruby
plugin :download_endpoint, storages: [:store], prefix: "attachments"
```

and then said

```ruby
mount Shrine::DownloadEndpoint => "/attachments"
```

in my routes.rb. However, I keep getting an error saying

```
uninitialized constant Shrine::DownloadEndpoint (NameError)
```

whenever I start the server. I also tried adding require lines

```ruby
require 'roda'
require 'shrine/plugins/download_endpoint'
```

but it does not really help. What am I missing? Thank you in advance!

**Comment by janko-m** [comment]
@bodrovis This error would happen if you loaded the `download_endpoint` inside a specific uploader, which would load the `DownloadEndpoint` inside the uploader, but not in global `Shrine` namespace. Is that perhaps the case?

Otherwise, could you please include all Shrine-related code?

**Comment by bodrovis** [comment]
That's interesting. Initially this plugin was loaded inside the initializer, globally. Then I moved it to the uploader. In both cases it wasn't working. Now I placed the line back into the initializer and it started to work. Anyways, thank you!

Also, I wanted to ask how to authenticate downloads with this plugin? I mean, I have many users in the system for example and not all of them should be able to download all the files. I already set Amazon's S3 ACL to "private" for uploading using http://shrinerb.com/rdoc/classes/Shrine/Plugins/UploadOptions.html and so now all files aren't available publically. There is also an option to generate expiring URLs to the file on Amazon which seems to be working as well. Now, the last thing is to check whether is user is permitted to actually receive this expiring link. Now that I think of it, maybe I don't need the download endpoint at all?..

**Comment by janko-m** [comment]
@bodrovis Yes, generating expiring URLs are generally a good alternative to authorizing downloads, and if that's good for you, then you don't need `download_endpoint`. Generally you should use `download_endpoint` if it's necessary, as serving files directly from Amazon S3 is so much simpler.

In case you decide you want to stick with `download_endpoint`, how to add authorization depends on which web framework and authentication library you're using. If you're using Devise, you unfortunately cannot use its [`authenticate`](http://www.rubydoc.info/github/plataformatec/devise/master/ActionDispatch/Routing/Mapper#authenticate-instance_method) router method, because it gives you access only to the user, and not the `request`, so you cannot extract the ID from the request path because you cannot access it.

However, you could theoretically try to nest another `constraints` inside Devise's `authenticate` block. So, let's say that you have User that `has_many :attachments`, where `Attachment` has a "file" Shrine attribute, and you want to check whether the request attachment belongs to the user (by retrieving the ID from the URL). This is how it might look like:

```rb
authenticate :user do
  constraints(AttachmentConstraint) do
    mount Shrine::DownloadEndpoint => "/attachments"
  end
end
```
```rb
class AttachmentConstraint
  def self.matches?(request)
    user = request.env["warden"].user(:user)
    attachment_id = path.match(%r{/attachments/(cache|store)/}).post_match

    AttachmentPolicy.new(user).can_download?(attachment_id)
  end
end
```
```rb
class AttachmentPolicy
  def initialize(user)
    @user = user
  end

  def can_download?(attachment_id)
    @user.attachments.any { |attachment| attachment.file.id == attachment_id }
  end
end
```

I hope that helps. I will close this as the original issue was resolved.

**Comment by bodrovis** [comment]
Thank you, Janko! :)
