### ISSUE TITLE
ActionView::Template::Error (storage :store isn't registered on PdfUploader):

### ISSUE THREAD

**Issue by codemilan** [janko-m/shrine#172]
I have been getting this error in development environment. I tried solution mentioned in comments in issue "https://github.com/janko-m/shrine/issues/155" but no luck. I tried changing config in environments/development.rb like config.cache_classes = true, config.eager_load = true but no luck.
When I removed all the caching code then i get "storage :cache isn't registered on PdfUploader" error.
Really confused ! is the issue related to gem or I have been doing things wrong.

**Comment by janko-m** [comment]
@codemilan This error can happen when your uploader somehow gets loaded before the Shrine initializer, because every uploader gets its own copy of registered storages, which is created upon inheritance. Consider the following hypothetical scenario:

```rb
# config/initializers/locales.rb
I18n.available_locales = Post::LOCALES
```
```rb
# config/initializers/shrine.rb
require "shrine"
require "shrine/storage/file_system"

Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new(Rails.root.join("public"), prefix: "uploads/cache"),
  store: Shrine::Storage::FileSystem.new(Rails.root.join("public"), prefix: "uploads/store"),
}
```
```rb
# app/models/post.rb
class Post < ActiveRecord::Base
  LOCALES = [:en, :de, ...]
  include PdfUploader::Attachment.new(:file)
end
```
```rb
# app/uploaders/pdf_uploader.rb
class PdfUploader < Shrine
  # ...
end
```

The error you described would happen in this scenario, because:

1. `locales.rb` initializer is executed first, because it's alphabetically lower than the `shrine.rb` initializer
2. `locales.rb` initializer references `Post` so it autoloads it
3. `Post` model references `PdfUploader` so it autoloads it
4. `PdfUploader` inherits from `Shrine`, but `Shrine.storages` is empty because the `shrine.rb` initializer that registers storages hasn't been run yet, so `PdfUploader` creates a copy of the empty storages
5. `shrine.rb` initializer gets run and registers the storages on `Shrine`, but `PdfUploader` was already loaded and has already created its copy when `Shrine.storages` was still empty, so `PdfUploader` storages list remains empty even after we modify `Shrine.storages`
6. error occurs when you try to use `PdfUploader` because there are no storages registered to it

This is what I think is happening in some way to you. You can confirm this by adding `p Shrine.storages` on top of `app/uploaders/pdf_uploader.rb`, and if it prints `{}` that means your Shrine initializer hasn't been run yet. In that case you can fix it by either not referencing your model in the initializers, or renaming `config/initializers/shrine.rb` to something like `config/initializers/1_shrine.rb` to give it alphabetical precedence so that it runs before any other initializer.

**Comment by janko-m** [comment]
I will close this, as what I said is the most likely issue, feel free to reopen if that wasn't the case (and in that case I would need to see all the Shrine-related code).

**Comment by codemilan** [comment]
Thankyou @janko-m, I understood the problem, and solved it by making shrine initializer load at first.

**Comment by antulik** [comment]
Had the same issue. Was very confusing at first, here is how you can debug and fix it yourself

in the uploader file add
```ruby

puts '+'* 50
puts 'uploader'
puts caller
class DocumentUploader < Shrine
#....
```
in the initializer file add similar code
```ruby
puts '+'* 50
puts 'initializer'

Shrine.storages = {
  cache: Shrine::Storage::S3.new(prefix: "cache", **s3_options),
  store: Shrine::Storage::S3.new(prefix: "store", **s3_options),
}
# ....
```

When you start your server you should see initializer to be loaded before uploader class. If it's not, check the printed stack trace. It shows the chain of files why Uploader class is loaded early.

In our case another initializer was referencing some other class which was loading our Uploader class.
