### ISSUE TITLE
is it possible to backup only originals of images?

### ISSUE THREAD

**Issue by okliv** [janko-m/shrine#191]
hi!

if i use a `backup_store` ([backup plugin](http://shrinerb.com/rdoc/classes/Shrine/Plugins/Backup.html))

```ruby
Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new('cache'),
  store: Shrine::Storage::FileSystem.new('public', prefix: 'attachments'),
  backup_store: Shrine::Storage::GoogleDriveStorage.new('master_images')
}
```

it saves a copy of my local files on a remote storage like expected. 

and if i enable `versions` plugin

```ruby
  process(:store) do |io|
    thumb = resize_to_limit!(io.download, 100, 100)
    { original: io, thumb: thumb }
  end
```
it backups all versions too.

but it would be enough (oh, i need it to work in this way) to store only originals with possibility to repopulate originals from backup with further local version recreations in case of direct action (button click, for example)

is it possible?

and one small question: can backup (uploading to remote) be implemented over an async job?

thanks

**Comment by janko-m** [comment]
At the moment it's not possible to use `backup` plugin for backing up specific versions. However, you can easily do this manually:

```rb
record = Record.create(attachment: file)
Shrine.storages[:backup_store].upload(record.attachment[:original], record.attachment[:original].id)
```

If you're promoting asynchronously using the `backgrounding` plugin, you could even push backing up to a separate job:

```rb
class PromoteJob
  def perform(data)
    attacher = Shrine::Attacher.promote(data)
    BackupJob.perform_async(attacher.get[:original].data) if attacher
  end
end
```
```rb
class BackupJob
  def perform(uploaded_file_data)
    uploaded_file = Shrine::UploadedFile.new(uploaded_file_data)
    Shrine.storages[:backup_store].upload(uploaded_file, uploaded_file.id)
  end
end
```

**Comment by janko-m** [comment]
Note that as per contribution guidelines, usage questions should be asked on the [Shrine Google group](https://groups.google.com/forum/#!forum/ruby-shrine). GitHub issues should be used only for reporting bugs in Shrine.

**Comment by okliv** [comment]
i hoped maybe it could become a feature request... sorry for violation of guidelines...

last question, please: in case of manual uploading i will need to implement manual repopulating from remote storage  too? maybe i can change a little bit a backup plugin to make it a `master_storage` plugin? Like...

``` ruby
#shrine/plugins/backup.rb:35
        def promote(*)
          result = super
          # store_backup!(result) if result   <<<< --- changes somewhere here
          store_backup!(result) if result.is_original?
          result
        end
```
and in other methods like `destroy`, `replace` and so on...

or somehow else? thanks again

**Comment by janko-m** [comment]
> i hoped maybe it could become a feature request... sorry for violation of guidelines...

No worries. The reason why I rejected the feature request is because I think it would add too much clutter for `backup` plugin to support uploading specific versions. I want other plugins to be unaware of versions, as this feature is added by a separate `versions` plugin, and I like to avoid plugins leaking into each other.

Note that regardless of whether the `backup` plugin is updated with versions support, it will never be able to be fully flexible. For example, if you want to upload to backup storage in a separate background job, you need to implement it yourself like I've shown above. For that reason I would like to keep `backup` plugin simple.

> is there at all the method to recreate files from backup?

I was experimenting with the idea of adding a `Storage#list` convention method, which would list all the ids from the storage. Each storage would have to implement that method. Then you could run something like:

```rb
main_storage, backup_storage = Shrine.storages.values_at(:store, :backup)

main_storage.list do |id|
  io = main_storage.open(id)
  backup_storage.upload(io, id)
end
```

But until then you will have to retrieve the files yourself. For FileSystem storage you can do it like this:

```rb
main_storage, backup_storage = Shrine.storages.values_at(:store, :backup)

main_storage.directory.find do |path|
  next unless path.file?
  id = path.relative_path_from(main_storage.directory).to_s
  io = main_storage.open(id)
  backup_storage.upload(io, id)
end
```
