### ISSUE TITLE
Retaining original filename

### ISSUE THREAD

**Issue by rsiddle** [janko-m/shrine#195]
There are cases when it's important to retain the original filename rather than a UUID. I see there is a `pretty_location` plugin that uses the UID, but no way of using the original filename?

```
require 'image_processing/mini_magick'

class ImageUploader < Shrine
  include ImageProcessing::MiniMagick
  plugin :store_dimensions
  plugin :processing
  plugin :versions
  plugin :delete_raw 

  process(:store) do |io, context|
    original = io.download

    large = resize_to_limit!(original, 800, 800)
    medium = resize_to_limit(original,  500, 500)
    small = resize_to_limit(original,  300, 300)

    { original: io, large: large, medium: medium, small: small }
  end
end
```

**Comment by janko-m** [comment]
Shrine stores metadata for each uploaded file, so since the original file is not kept it has nowhere to store the original filename (it wouldn't make sense to store it one of the versions because it's not their original filename).

If you would like to retain the original filename in this case, I would recommend using the [metadata_attributes](http://shrinerb.com/rdoc/classes/Shrine/Plugins/MetadataAttributes.html) plugin to store the filename of the original file in a separate column.

```rb
class ImageUploader < Shrine
  plugin :metadata_attributes, filename: :original_filename
end
```

With the above configuration you just have to create the `<attachment>_original_filename` column on the model, and Shrine will automatically synchronize it whenever a new file is assigned or removed.
