### ISSUE TITLE
Removing metadata

### ISSUE THREAD

**Issue by Grafikart** [janko-m/shrine#206]
First I want to thanks you for your work. I'm currently migrating my database from CarrierWave to Shrine ;)

One thing that still bother me is the JSON stored in the `_data` field. I don't get what purpose serves the metadata field and I wonder if I could remove it completly ?
I don't need the actual code (I could write a plugin to remove it I guess) but I want to know if it's used somewhere else before breaking everything ;).

If it's not "necessary" I would expect the `metadata` key to be added **only** if the plugin `add_metadata` right ?

**Comment by hmistry** [comment]
It stores file informational data like file id, which storage unit the file is stored in, and any additional metadata like filename, size, mime type, etc. The `add_metadata` plugin is to add additional custom metadata.

Have a look at these links: 
- https://twin.github.io/better-file-uploads-with-shrine-uploader/ (under UploadedFile section)
- https://twin.github.io/better-file-uploads-with-shrine-metadata/

**Comment by Grafikart** [comment]
My goal is to only store the filename in my database (or a JSON containing filenames per version)

```json
{
    "original": "123.jpg",
    "thumb": "123_thumb.jpg"
}
```

Since I know I'll only use `:store` as my storage. I'm currently trying to create a plugin that overwrite `convert_to_data`. I close this issue since I realize it's quite specific to my use case, and it may not be necessary to everyone

**Comment by janko-m** [comment]
> One thing that still bother me is the JSON stored in the `_data` field. I don't get what purpose serves the metadata field and I wonder if I could remove it completly ?

Shrine in some places uses certain metadata if available, but they are never be required. Some places where metadata is used:

* `validation_helpers` plugin uses `size`, `mime_type`, and `filename` metadata values in `#validate_(max|min)_size` and `#validate_(mime_type|extension)_(inclusion|exclusion)` methods 
* `Shrine::Storage::S3` uses `mime_type` and `filename` plugins for setting `Content-Type` and `Content-Disposition` object headers
* `rack_response` plugin uses `size`, `mime_type`, and `filename` metadata values for setting `Content-Length`, `Content-Type` and `Content-Disposition` response headers, though `Content-Length` and `Content-Type` will in most cases be set correctly even if the corresponding metadata values are missing.

> If it's not "necessary" I would expect the metadata key to be added only if the plugin add_metadata right ?

The plugins that set `metadata` values are `determine_mime_type`, `store_dimensions`, and `add_metadata`. The reason why Shrine extracts and stores these basic metadata by default is because one might need them later on. For example, one might want to show size, type or filename of the file, and in case file uploads are already live the metadata values need to be backfilled (note that filename cannot be backfilled as it cannot be determined from the uploaded file). In these cases it's convenient to already have certain basic metadata saved.
