### ISSUE TITLE
Metadata overwritten after process(:store) used

### ISSUE THREAD

**Issue by rsiddle** [janko-m/shrine#211]
The `add_metadata` function saves the data on the cached model, but when `process(:store)` is used, the `metadata` is overwritten (using `text/plain` file).

```  plugin :processing
  plugin :add_metadata

  process(:store) do |io, context|
    original = io.download
    tmp = Tempfile.new(['tmp', '.txt'])
    lines = original.read # changed some line information and pushing back to the temporary file.
    tmp.puts(lines)
    tmp
  end

  add_metadata do |io, context|
    original = io.download
    data = original.read
    line_count = data.split("\r").size
    {
      'encoding' => data.encoding.name,
      'encoding_valid' => data.valid_encoding?,
      'line_count' => line_count
    }
  end
```

I see that when we try to `read` the `Tempfile` the second time around, using `io.read`, it returns `""`. The [Custom processing docs](https://github.com/janko-m/shrine#custom-processing) appear to use Tempfiles.

**Comment by hmistry** [comment]
The output of the process block needs to be a hash containing the key-value pair of attribute name to file. In that link it is `{video: video, screenshot: screenshot}` or a better form is ` {video: video_file, screenshot: screenshot_file}`. This hash gets converted into json and stored in the model `data` property.

In your case it's probably something like:
```ruby
  process(:store) do |io, context|
    original = io.download
    tmp = Tempfile.new(['tmp', '.txt'])
    lines = original.read # changed some line information and pushing back to the temporary file.
    tmp.puts(lines)
    { original_text_file_key: tmp } # if you want to override the original file
    # or { original_text_file_key: original, modified_text_file: tmp } if you want to keep both
  end
```

**Comment by janko-m** [comment]
> The output of the process block needs to be a hash containing the key-value pair of attribute name to file.

@hmistry Note that the result of processing can also be a single file, this example is fine. Shrine supports 1-1 processing, as well as 1-N or M-N processing.

> I see that when we try to read the Tempfile the second time around, using io.read, it returns "". 

@rsiddle The issue is that you're not rewinding the file after writing to it in the processing block. You need to add a `tmp.rewind` before returning it:

```rb
  process(:store) do |io, context|
    original = io.download
    tmp = Tempfile.new(['tmp', '.txt'])
    lines = original.read # changed some line information and pushing back to the temporary file.
    tmp.puts(lines)
    tmp.rewind # <=== rewind the file
    tmp
  end
```

Without rewinding you'll be getting `""` when you try to read from it, because the position is at the end of file.

Note that in your `add_metadata` example you shouldn't be using `io.download`, because most of the files that are passed for metadata extraction will be raw files, and they don't respond to `#download`.

```rb
  add_metadata do |io, context|
    data = io.read
    line_count = data.split("\r").size
    {
      'encoding' => data.encoding.name,
      'encoding_valid' => data.valid_encoding?,
      'line_count' => line_count
    }
  end
```

Shrine will by default never pass a `Shrine::UploadedFile` object for metadata extraction; when a cached file is re-uploaded to storage, Shrine simply copies the cached file's metadata that has already been extracted. The only time Shrine will re-extract metadata from a `Shrine::UploadedFile` is if you load the `restore_cached_data` plugin, but even in that case you don't need to explicitly `#download` it in this scenario, as `Shrine::UploadedFile` objects are also IO objects that respond to `#read`.
