### ISSUE TITLE
String.new ascii encoded vs utf8

### ISSUE THREAD

**Issue by hmistry** [janko-m/shrine#218]
Came across Sam's comment [here](https://github.com/MiniProfiler/rack-mini-profiler/pull/319#issuecomment-342938213) where he stated:

> Huge warning on string.new, you get an ascii encoded string back, always
> prefer “”.dup which is utf8
> 

Does this pose any problems in Shrine?

**Comment by janko-m** [comment]
This shouldn't pose any problems with Shrine. First, note that `String.new` returns a string in _binary_ encoding, not ASCII encoding.

```rb
[1] pry(main)> String.new.encoding
=> #<Encoding:ASCII-8BIT>
[2] pry(main)> Encoding::BINARY
=> #<Encoding:ASCII-8BIT>
[3] pry(main)> Encoding.find("ascii")
=> #<Encoding:US-ASCII>
```

The confusion is easily made because both encodings have `ASCII` in their name, but `ASCII-8BIT` is just the name that Ruby gives to binary encoding, and as far as I know it's not a name of any official encoding.

Second, I noticed some time ago that a string encoding changes when necessary:

```rb
[1] pry(main)> string = "foo"
=> "foo"
[2] pry(main)> string.encoding
=> #<Encoding:UTF-8>
[3] pry(main)> require "securerandom"
=> true
[4] pry(main)> string << SecureRandom.random_bytes
=> "fool&'\x90\xAAQe\xBC\xD9\xEB\xAD\x8D\xEB6\v\x10"
[5] pry(main)> string.encoding
=> #<Encoding:ASCII-8BIT>
```

Third, the only place where `String.new` is used in `signature` plugin, where it's used as a buffer for reading file content in chunks. And in the case of reading file content, binary encoding is even _desireable_. There is a great [RubyTapas episode #470](https://www.rubytapas.com/2017/03/13/episode-470-binary-mode/) in which Avdi explains why it's always safer to read in binary mode; and binary *encoding* is related to binary mode, because when file is opened in binary mode, the read content is always returned in binary encoding. TL;DR it's more cross-platform and generic.

**Comment by vanboom** [comment]
Adding a note while converting from Carrierwave.  Consider a simple PNG image file attachment.  Shrine reads the file as UTF-8 differently than Carrierwave which returns ASCII-8BIT

In Carrierwave...
```ruby
s = uploaded_file.read
puts s.encoding
> ASCII-8BIT
```
In Shrine...
```ruby
s= uploaded_file.read
puts s.encoding
> UTF-8
```

**Comment by jrochkind** [comment]
I wonder if what @vanboom observes is actually a bug, if it's reproducible? Binary data should be returned as ASCII-8BIT.

**Comment by vanboom** [comment]
I'm using Rails 5.2.4.5, Ruby 2.5.0.  Google storage.  I will do some testing with file storage and see if there is a difference w/r to storage type.
