### ISSUE TITLE
How to model associations? 

### ISSUE THREAD

**Issue by j-jackson** [janko-m/shrine#229]
This is probably more related to my lack of experience with rails ActiveRecord than shrine so please feel free to close if its not relevant.

I'm having trouble figuring out how to setup my models as all the examples I have found use very simple one-to-one associations.

Lets say I have a **Post** model with a single cover image and many images:

```ruby
 hero_image: image_data
 images: image_data 
```

And then have a **User** model with a single avatar image:

```ruby
  avatar: image_data
```

How would you model this? I thought a polymorphic association might be a good solution for the **Post** models ``has_many images`` as it is likely that I will need a similar setup for other models, but how would I setup the single images such as the ``hero_image and ``avatar?  Would they all be stored I the seperate ``Images`` model or only the ones with multiple images?

**Comment by mvasin** [comment]
Hi, @j-jackson! Please have a look at readme, it says the issues area is actually for issues (bugs etc), questions should go to google group.

**Comment by janko-m** [comment]
First of all, `Post#images` is the only case where you *need* to have a separate `Post.has_many :images` association, but you can also easily have `Post.has_one :hero_image` and `User.has_one :avatar` if you want to. In any case you'll probably want to use `accepts_nested_attributes_for` to make creation a bit easier. Whether or not attachments are separate records doesn't really change anything in how Shrine works or how to set it up, you still have an attachment on a record.

Whether the associations will be polymorphic or not depends entirely on your requirements. If you want to have associations for all three kinds of images, you will need to add some kind of `identifier` because now the same model (`Post`) has multiple attachments. Or if you realize that you want to have different logic for "hero images" and "avatars", then you might want to use a different record and/or uploader. Shrine normally supports uploader inheritance, so you have all tools in the shed for whichever route you want to go to.

**Comment by j-jackson** [comment]
Thanks @janko-m thats perfect.
