### ISSUE TITLE
Cannot access cached_data from nested form

### ISSUE THREAD

**Issue by studiorooster** [janko-m/shrine#232]
Sorry to post this here but I am out of options - no real help on Stack Overflow.  Here is the entire post on Stack Overflow that will go into much more detail than I will here.  https://stackoverflow.com/questions/47736859/rails-5-nested-form-image-upload-cache-and-view

I am using the cocoon gem to handle a nested form in my application, I can upload an image and it persists to the database, but I cannot access the cached data.  I am using the normal syntax `<%= f.hidden_field :photo_one, value: @product.cached_photo_one_data %>` which works without nesting.  I am hoping you can help me because I really like using Shrine. I attached a screen shot of the error as well on the above SO link.  Thank you.

**Comment by hmistry** [comment]
The problem I'm seeing in the code is you're trying to access a method `photo_one_*` in `@product` which I'm assuming is a `Product` class and `Product` class does not contain that method. `Variation` class is the one that contains that method, so you really want to be doing is `@product.variations[index].photo_one_*`.

**Comment by studiorooster** [comment]
@hmistry That worked great, thank you.  Once more issue I am having. I don't get the errors now and I can reference the images as thumbnails in the form.   But the hidden checkbox code I have to delete the image is not working.

`
<div class="input-checkbox">
                        <input name="product.variations[remove_photo_one]" type="hidden" value="0">
                        <input type="checkbox" name="product.variations[remove_photo_one]" id="input-assigned-0">
                        <label for="input-assigned-0"></label>
                    </div>
                    <span>Remove Image</span>
`

**Comment by hmistry** [comment]
@studiorooster This is not a shrine bug nor issue but really a Rails and OO programming fundamentals issue. I helped because it was quick but you should really seek help on SO or a more general programming forum. 

`product` is an instance of `Product` and has only the methods available to that class. `product.variations` is a collection data structure (think like an array) and you access individual values by passing an index. Then if the value of the collection variations is an object like `photo` in your case you can call methods on the value that are available to its class in this case `remove_photo_one`. Think about this and what you have written above and what you want to do... you have all the info to find the answer by self. Play around in the rails/web console. Good luck. 😃 

A note: for future help on this, please post on SO or ask a friend. If you have an issue actually related to Shrine after following the documentation instructions on [shrinerb.com](http://shrinerb.com), post in the [groups.google.com/groups/ruby-shrine](https://groups.google.com/forum/#!forum/ruby-shrine) and we'll try to help.

**Comment by janko-m** [comment]
@studiorooster This is not a bug in Shrine, you're not generating correct input names for `accepts_nested_attributes_for` to work once the form is submitted. `accepts_nested_attributes_for` accepts parameters only in certain format, so you have to be precise in how you're generating the form input names; check the request parameters in the logs to see how your format differs from the documented format. See [shrine-rails-example](https://github.com/erikdahlstrand/shrine-rails-example) for an example of the correct format for `accepts_nested_attributes_for`.

In the future if you're unsure whether something is a bug with Shrine, please post to the Google group first; GitHub issues should be used only for bug reports.
