### ISSUE TITLE
Issue when trying to upload cached s3 file

### ISSUE THREAD

**Issue by Chocksy** [janko-m/shrine#24]
I'm trying to do `@user.avatar = params[:user][:avatar]` on an avatar file that was uploaded via jquery.fileupload. The params look like this:
`{"user"=>{"avatar"=>{"id"=>"f52c607d73a78858532eefdd303ffa8685d5771edd821a9e256dbd88322a", "storage"=>"cache", "metadata"=>{"size"=>"97874", "filename"=>"skylanders_swap_force_ps4-01.jpg", "mime_type"=>"image/jpeg"}}}}`

The problem is that the gem can't pick this up as an io:
`Shrine::InvalidFile: {"id"=>"f52c607d73a78858532eefdd303ffa8685d5771edd821a9e256dbd88322a", "storage"=>"cache", "metadata"=>{"size"=>"97874", "filename"=>"skylanders_swap_force_ps4-01.jpg", "mime_type"=>"image/jpeg"}} is not a valid IO object (it doesn't respond to `read(length, outbuf)`, `eof?()`, `rewind()`, `close()`)
from /Users/razvanciocanel/.rvm/gems/ruby-2.1.5@rails4/bundler/gems/shrine-39c045174f49/lib/shrine.rb:357:in `_enforce_io'`

This worked with version 0.9.0 but now it does now with version 1.0.0.

What changed? 

----

Other details:

shrine.rb file:
```
require "shrine"
require "shrine/storage/file_system"
require "shrine/storage/s3"
require "shrine/plugins/activerecord"

s3_options = {
  access_key_id:     ENV['AWS_ACCESS_KEY_ID'],      # "xyz"
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],  # "abc"
  region:            ENV['AWS_REGION'],             # "eu-west-1"
  bucket:            ENV['AWS_BUCKET'],             # "my-app"
}

if Rails.env.development?
  s3_options.merge!({
    endpoint:           ENV["AWS_ENDPOINT"],
    host:               "#{ENV["AWS_ENDPOINT"]}/#{ENV["AWS_BUCKET"]}/",
    force_path_style:   true
  })
end

Shrine.storages = {
  cache: Shrine::Storage::S3.new(prefix: "cache", **s3_options),
  store: Shrine::Storage::S3.new(prefix: "store", **s3_options),
}

Shrine.plugin :direct_upload, presign: true, max_size: nil #20*1024*1024
Shrine.plugin :background_helpers

Shrine::Attacher.promote { |data| ShrineUploadJob.perform_async(data) }
Shrine::Attacher.delete { |data| ShrineDeleteJob.perform_async(data) }
```

**Comment by janko-m** [comment]
What changed is that this functionality got extracted into a separate `parsed_json` plugin. The reason for this is that I intended to make a plugin for enabling multiple files uploads in the same column, and having this functionality in the base made things more complicated, so I thought it would be more easily managed.

I initially thought that this would only be required in the case where a JSON string is submitted in the form, and the web framework parses that JSON. However, I see that this use case is completely valid, and I also used this functionality in the existing app (which I didn't update with the 1.0 release). Even though in the meanwhile I've put the plugin for multiple files on hold (I find it too difficult to implement properly, and not important enough at the moment), I would still like to have this path open.

I'm not sure if it was the right decision to move this into a plugin, I will see if adding it back would still leave the path open for the potential multiple files plugin. Otherwise I will update the documentation to be explicit about accepting only JSON strings (and the example app as well).

**Comment by Chocksy** [comment]
@janko-m ok ignore this it seems because of me setting avatar_data column with some json/hash string and then trying to set `@user.avatar` again was giving me that error. I'll close this.

**Comment by mma7** [comment]
i am having the same issue i keep getting this error :

`"dffff7b0f6f99336b6f1e4f933485135.jpeg" is not a valid IO object (it doesn't respond to #read, #eof?, #rewind, #close)
 `
in my controller i receive the json as a string from a hidden input field :

```
"photo"=>
  {"image"=>"{\"id\":\"dffff7b0f6f99336b6f1e4f933485135.jpeg\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"image-20-09-16-10-44-1.jpeg\",\"size\":146670,\"mime_type\":\"image/jpeg\"}}"}

```

the code in my controller is like this:

```
def photo_params
   params.require(:photo).permit(:image)
end
image = ActiveSupport::JSON.decode(photo_params[:image]).with_indifferent_access
@post.photos.create(image: image)

```

even if i try : 

```
photo = Photo.new
photo.image = image
```
i keep getting the same error!

That's just a modified part of the code otherewise it will be long( i am using form objects with virtus)

Thanks in advance

**Comment by vcavallo** [comment]
Hello.

I'm having the same error.

```
Shrine::InvalidFile (<ActionController::Parameters {"id"=>"988c14e239761adbec83c00f91ce0e42.png", "storage"=>"cache", "metadata"=><ActionController::Parameters {"filename"=>"tiny.png", "size"=>148, "mime_type"=>"image/png", "width"=>3, "height"=>3} permitted: true>} permitted: true> is not a valid IO object (it doesn't respond to         #read, #eof?, #rewind, #close)):
```

As far as I can tell (this is my first run-in with Shrine, trying to replace the half-baked ActiveStorage) I'm doing fairly normal stuff implementing a direct upload solution with S3. I'm expecting this json reference to the cached version (which is getting uploaded to S3 just fine) to trigger the full save / promote behavior, but instead I'm getting this error.

Is the issue here actually the `ActionController::Parameters` bit getting in the way?

**Comment by vcavallo** [comment]
Fixed by calling `.to_json` on the params hash in the controller.

**Comment by jrochkind** [comment]
@vcavallo Alternatively, I believe you just need to add the `parsed_json` plugin to shrine, such as with `Shrine.plugin :parsed_json`. 

Or, sometimes instead of sending these things back as separate params, people send them to Rails as a serialized JSON string in the first place -- which is what most of the shrine examples show -- in which case it would just work. 

Any of those approaches should be fine.

**Comment by vcavallo** [comment]
thanks. i actually tried parsed_json right before this and for some reason it didn’t make any difference.
