### ISSUE TITLE
filenames become incorrectly formatted when using s3 direct upload

### ISSUE THREAD

**Issue by dauncing** [janko-m/shrine#249]
[I tried to post this in the Google Group but it didn't seem to work.]

Firstly, I wanted to say thanks for making a great tool for Ruby.

With direct S3 uploading, the filenames are incorrectly formatted when I try to redownload them from S3. 

For example

“Fugiat Ab Est Consequatur Saepe” at Aut Nihil Culpa Quidem Ut Delectus, 2017.pdf
redownloads as
“Fugiat Ab+Est+Consequatur+Saepe”+at+Aut+Nihil+Culpa+Quidem+Ut+Delectus%2C+2017.pdf

Note that the filename has open/close quotes, not the normal quotes. Weirdly the first space is correct, but the rest turn into + . It seems like just a few random characters don't appear correctly, like ()^,'"

I also noticed that if I upload files to S3 via the [web-based console](https://s3.console.aws.amazon.com/s3/buckets/) I get almost the exact same problem.

Doesn't seem to be caused by the encode_content_disposition method in storage/s3.rb .

The filename is stored correctly in the database:
```
{
  "original": {
    "id": "doc\/591\/docshrine\/original-be415b340c9fef6c2ba4ad1d6583632e.pdf",
    "storage": "store",
    "metadata": {
      "size": 536018,
      "filename": "\u201cFugiat Ab Est Consequatur Saepe\u201d at Aut Nihil Culpa Quidem Ut Delectus, 2017.pdf",
      "mime_type": "application\/pdf"
    }
  }
}
```

But the metadata looks weird in S3:

`attachment; filename="%E2%80%9CFugiat Ab+Est+Consequatur+Saepe%E2%80%9D+at+Aut+Nihil+Culpa+Quidem+Ut+Delectus%2C+2017.pdf"
`

My javascript:

```
Dropzone.autoDiscover = false;

$(document).ready(function(){
    var myDropzone = new Dropzone('div#docDrop', { 
      url: '#',
      // Need to override the parameter so that it plays nicely
      paramName: 'file',
      maxFiles: 800,
      maxFilesize: 4900,
      timeout: 0,      
      // We are manually triggering queue processing
      autoProcessQueue: true,
      autoQueue: false,
      createImageThumbnails: false,
      parallelUploads: 3,
      addRemoveLinks: true,
      dictRemoveFile: "✕",
      dictInvalidFileType: "Format not supported.",
      previewTemplate: docTemplate(),      
      init: function() {
        myDropzone = this

        // Whenever a file is added, get the presigned S3 URL and attach it
        myDropzone.on('addedfile', function(file) {

          // Set the extension and add a date to avoid any strange caching
          // This options hash is sent to the presign URL to get S3 information
          options = {
            filename: file.name,
            _: Date.now()
          };

          $.ajax({
            url: '/presign',
            data: options,
            type: 'GET',
            success: function(response){
              file.additionalData = response['fields'];
              myDropzone.options.url = response['url'];
              myDropzone.enqueueFile(file);
            }
          });

        });

        // Before sending a file, set the formData to the S3 fields stored above
        myDropzone.on('sending', function(file, xhr, formData) {
          $.each(file.additionalData, function(k, v) {
            formData.append(k, v);
          });
        });    

        myDropzone.on('success', function(data, asdf) {
          doc = {
            id: data.additionalData.key.match(/cache\/(.+)/)[1],
            storage: 'cache',
            metadata: {
              size: data.size,
              filename: data.name,
              mime_type: data.type
            }
          };

          var data = data;

        // After a file is successfully uploaded, we need to send it back
        // to Rails so that it can be attached to the Doc model
          $.ajax("/docs", {method: 'POST', data: {doc: {docshrine: JSON.stringify(doc)}}})
            .done(function(response) { 
              vals = $('.doc_list').val();
              if (vals.length) {
                vals = vals.split(',');
              } else {
                vals = new Array();
              }
              vals.push(response.id);

              $(data.previewElement).addClass('dz-success').
                attr('data-docId', response.id).
                find('.dz-doc-filename').attr('href', response.original);

              updateDocFields(vals);   
              myDropzone.processQueue();         
            });

        });
      }
    });
  }
});


function updateDocFields(vals) {
  $('.record > form').change();
  $('.doc_list').val(vals.join(','));  
}

function docTemplate(){
  return '<div class="dz-preview">' +
  '  <a class="dz-doc-filename" target="_blank"><span data-dz-name></span></a>' +    //<span class="icon-file-empty"></span>
  '  <div class="dz-progress"><span class="dz-upload" data-dz-uploadprogress></span></div>' +
  '  <div class="dz-error-message"></div>' +
  '</div>';
}
```

config/initializers/shrine.rb

```
require "shrine"
require "shrine/storage/s3"

if !Rails.env.production?
  require "dotenv" 
  Dotenv.load!
end

s3_options = {
  access_key_id:     ENV.fetch("AWS_ACCESS_KEY_ID"),
  secret_access_key: ENV.fetch("AWS_SECRET_ACCESS_KEY"),
  region:            ENV.fetch("AWS_REGION"),
  bucket:            ENV.fetch("S3_BUCKET_NAME"),
}


Shrine.storages = {
  cache: Shrine::Storage::S3.new(prefix: "cache", upload_options: {acl: "public-read"}, **s3_options),
  store: Shrine::Storage::S3.new(prefix: "store", upload_options: {acl: "public-read"}, **s3_options),
}
Shrine.storages[:cache].url(public:true)
Shrine.storages[:store].url(public:true)

Shrine.plugin :activerecord
Shrine.plugin :logging, logger: Rails.logger
Shrine.plugin :presign_endpoint, presign_options: -> (request) do
  filename     = request.params["filename"]

  {
    content_disposition: "attachment; filename=\"#{filename}\""
  }
end
Shrine.plugin :presign_endpoint, presign_location: -> (request) do
  "#{SecureRandom.hex}_#{request.params["filename"]}"
end

Shrine.plugin :backgrounding
Shrine.plugin :default_url_options, store: {public: true}


Shrine::Attacher.promote { |data| PromoteJob.perform_async(data) }
Shrine::Attacher.delete { |data| DeleteJob.perform_async(data) }

```

doc_uploader.rb

```
class DocUploader < Shrine
  plugin :determine_mime_type
  plugin :remove_attachment
  plugin :store_dimensions
  plugin :validation_helpers
  plugin :pretty_location
  plugin :processing
  plugin :versions, fallback_to_original: true

  Attacher.default_url do
    "/delayed_processing.png"
  end

  process(:store) do |io, context|
    {original: io}
  end

end

```

Any ideas of how to make all filenames appear correctly when redownloading?

Thanks!

**Comment by janko-m** [comment]
@dauncing Thank you for such a detailed issue report.

> With direct S3 uploading, the filenames are incorrectly formatted when I try to redownload them from S3.

This has actually been [fixed](https://github.com/janko-m/shrine/commit/7eea6146c3f2834241fb2bdcc55b020d1b253d47) in Shrine 2.9.0. It won't affect the existing uploads (because `:content_disposition` is a static object attribute), only new uploads.

> But the metadata looks weird in S3

This is because Shrine URI-encodes the filename for `:content_disposition` (that's where the bug with `+` symbols came from). The reason for that is to avoid non-ASCII characters, as they [break AWS SDK's signature generation](https://github.com/aws/aws-sdk-ruby/issues/1230#issuecomment-261198298). This should be fine, because browsers seem to automatically URI-decode the filename on download.

> [I tried to post this in the Google Group but it didn't seem to work.]

Hmm, I'm not sure why is that 🤔. The `asdf` post you tested with was in fact posted, but the other one wasn't, I didn't even get any "pending approval" notification.

**Comment by dertel** [comment]
Thanks for the quick reply! 

Updating Shrine to 2.9 fixed the problem with spaces. However I'm still finding that all other URI-encoded characters are not decoding on many browsers/OSes when I try to redownload. 

I played with encode_content_disposition to only encode doublequotes ". Even if I don't escape filename at all it doesn't break the upload. All characters render perfectly except doublequotes, which turn into underscores. But I had weird behavior in some browsers when saving files that had the unescaped doublequote.

So for now, unless I find more bugs, I will patch line 425 with simply `filename.gsub('"', '\'')` 

Judging from the issue you linked to and other related discussions, it seems like this issue is partly outside the scope of Shrine.

Thanks again.

**Comment by janko-m** [comment]
> However I'm still finding that all other URI-encoded characters are not decoding on many browsers/OSes when I try to redownload.

Oh, that's unfortunate. Yeah, I remember now that someone mentioned Firefox and perhaps even Chrome. I was hoping that other browsers do it as well.

> Judging from the issue you linked to and other related discussions, it seems like this issue is partly outside the scope of Shrine.

Yeah, the issue is entirely in the aws-sdk-s3 gem, if I include non-ASCII characters, then aws-sdk-s3 gem will generate a different signature than the S3 service, and S3 will return an error response saying the signature was invalid.

Since this issue was effectively marked as "wontfix" on the aws-sdk-s3 repo, I decided that it was better to ensure that all uploads succeed, even if that means thae some characters might not display properly. But maybe it would be more correct to simply strip away all non-ASCII characters and only URI-encode the double quotes, I don't have a strong opinion about that.
