### ISSUE TITLE
Multiple Stores with ORM

### ISSUE THREAD

**Issue by zamith** [janko-m/shrine#26]
Is it possible to specify a store for each `Uploader` to be used with an ORM?

**Comment by janko-m** [comment]
If I understand you correctly that you want different uploaders to have different cache and store, then yes. There is a `default_storage` plugin, where you can specify which storage is used for cache and/or store:

```rb
Shrine.storages[:custom_cache] = ...
Shrine.storages[:custom_store] = ...
```
```rb
class MyUploader < Shrine
  plugin :default_storage, cache: :custom_cache, :store: :custom_store
end
```

**Comment by zamith** [comment]
Hum... I had not realized I could specify a plugin for an uploader. Cool.

I ended up using one S3 bucket, and using pretty_location to specify per uploader a directory where to store. It's working, but do you see any issues with that?

**Comment by janko-m** [comment]
Is it that for one uploader you left the default storing (which is flat, all files are stored in the top-level directory), and with other uploader you're using pretty_location? I don't see any issues with that, maybe you would rather want to have 2 separate storages which use the same S3 bucket, but just different directories:

```rb
Shrine.storages[:store] = Shrine::Storage::S3.new(prefix: "foo", **s3_options)
Shrine.storages[:custom_store] = Shrine::Storage::S3.new(prefix: "bar", **s3_options)
```

But that's just for better visibility, I don't think there should be any issues with your current solution.

I will close this now since I like to use GitHub issues only for bugs, but feel free to continue the discussion or ask any more questions you have on the [mailing list](https://groups.google.com/forum/#!forum/ruby-shrine).

P.S. I knew that your name sounded familiar, and when I looked at your GitHub profile I remembered that you were the organizer of the Ruby conference in Braga :)

**Comment by zamith** [comment]
Yes I am. :) I remember you too. ;) I might give that a go. Thanks.

**Comment by ahmgeek** [comment]
@janko-m glad you knew each other from a areal life, my question though, could upload images to `cache` on heroku for instance to perform some image optimization, then upload the final product to `store` which will be s3 ?
if yes, could put some hints ?

**Comment by janko-m** [comment]
Yes it can, the `Shrine#process` method is called both when uploading to `cache` and uploading to `store`, so you can do:

```rb
class ImageUploader < Shrine
  def process(io, context)
    case context[:phase]
    when :cache
      optimize_image(io)
    when :store
      # additional processing
    end
  end

  def optimize_image(file)
    # ...
  end
end
```

**Comment by ahmgeek** [comment]
Thanks a lot buddy <3
after reading [this](http://shrinerb.com/rdoc/files/README_md.html#label-Processing) I've noticed that when `process` is called it downloads the file first right ? I guess that fixes the issue with say AWS S3, as they don't support processing in the buckets. if that's the way then you're awesome, if now, you're awesome anyway.
why you recommended that the process shouldn't done on caching though ?

**Comment by janko-m** [comment]
Actually, `#process` doesn't download the file. On caching `io` will be whatever you assign as the attachment, which is usually a file (in Rails an `ActionDispatch::Http::UploadedFile`). On storing `io` will typically be a `Shrine::UploadedFile` which represents a file uploaded to `:cache`. It's not automatically downloaded because it sometimes doesn't need to (e.g. with S3 on both cache and store Shrine will issue an S3 copy request instead of downloading and reuploading). That's why you have to call `io.download` there if you want to do processing.

The reason processing on caching isn't recommended is because caching happens before file validations are run. So if you have validations on maximum filesize and dimensions, those will be run only after the file is cached, so the attacker can freely upload arbitrarily large images.

But you can use the `recache` plugin, which caches your files again before saving the record, triggering `#process` again (with the `:recache` phase). The use case for this plugin is if you're using backgrounding, to be able to do some processing in the foreground before kicking off a background job.

**Comment by ahmgeek** [comment]
Well, in my current project we depends on images heavily, but we need to process the image to reduce the size lossless compression and the like, I use toy's gem [image_optim](https://github.com/toy/image_optim) , so the processing needs to be in background, we use dragonfly as the main uploader and default image gem right now, but most of the gem don't support that out of the box. along with S3 processing issue. I've read the debate with you about a separate image server but still exploring my options.

**Comment by janko-m** [comment]
I'm actually not against the idea of a separate image server, I think that an image server should be an *addition* to libraries like Shrine, not a replacement. For example, I've created [shrine-cloudinary](https://github.com/janko-m/shrine-cloudinary) for integration with the [Cloudinary] service, which is an image server. Also, in my opinion it pays off more to use a dedicated image server like Cloudinary, since you don't have to worry about scaling (there is a free plan). But that's depending on how specific processing you need, and other things.

I'm not sure from your comment if one of the things I mentioned above solves your problem.

**Comment by ahmgeek** [comment]
it helped man, I appreciate it, Thanks :kiss:
