### ISSUE TITLE
Moving files on S3 from cache to store

### ISSUE THREAD

**Issue by mkcode** [janko-m/shrine#36]
I have my application setup and working very nicely with direct to s3 uploads using shrine.

Looking into the `delete_uploaded` plugin, I notice that it does not support `UploadedFile` and therefore will not operate on S3 cache to S3 store.

I notice the `move_to` method on `aws-sdk`: http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html#move_to-instance_method

Have you evaluated this at all? I would think that we can get the functionality of `delete_upload` on s3 to s3 copying if we use this `move_to` method.

But also, I notice `move_to` just calls `copy_to` and then `delete`, leading me to think that all the copy operations are synchronous an therefore ok to use?

Have you evaluated this at all? If it is possible, do you think this should be part of the `delete_uploaded` plugin or a separate plugin?

**Comment by janko-m** [comment]
Yeah, I have gave this topic a long thought, it took me a long time to reach a decision, and am sometimes still reevaluating this choice but always arrive to the same conclusion.

The reason why I don't allow deleting `UploadedFile` in the `delete_uploaded` plugin is because cached files in general shouldn't be deleted on upload, but rather the cache storage should be cleared periodically in a recurring task. To explain the reason for this, consider the following scenario:

```rb
class ImageUploader < Shrine
  def process(io, context)
    if context[:phase] == :store
      tempfile = io.download
      original = io # cached file (instance of Shrine::UploadedFile)
      medium = resize_to_limit(tempfile, 500, 500)
      small = resize_to_limit(tempfile, 300, 300)

      {original: original, medium: medium, small: small}
    end
  end
end
```

I find this scenario to be very common. If the `delete_uploaded` plugin would delete `Shrine::UploadedFile` instances, storing the above hash of versions would first upload the `:original` cached file (and delete it), and then upload `:medium` and `:small`. This means that if you're doing backgrounding, the cached file that was potentially in use (for graceful degradation until the background job finishes) would get deleted *before* storing finished and the record is updated, which would momentarily result in a broken link on the cached file.

This may not be a big deal in low-traffic applications, but the bottom line is that it would make your app sometimes look broken, and the bug is very subtle (you wouldn't get an error report for it), so I wanted to ensure that it can never happen with Shrine (unless you're using the `moving` plugin, but it's not intended to be used with versions anyway).

Using `move_to` would only theoretically make sense adding to the `moving` plugin, but as you already noticed in the implementation, it copies then deletes (two HTTP requests). Since copying is already [done automatically](https://github.com/janko-m/shrine/blob/01f20b64ef4a97a35080a977312e05ae7812e2db/lib/shrine/storage/s3.rb#L121-L122) when a cached S3 file is stored to S3, the `moving` plugin gives you exactly the same behaviour as `move_to` would give, so there wouldn't be any benefit in using it.

For your case, if you're not doing any processing, and you would want the cached S3 file to be deleted immediately on upload, you can use the `moving` plugin:

```rb
plugin :moving, storages: [:store]
```

Note that this will add an additional HTTP request (deletion) on storing. Alternatively you can just [setup S3 to automatically delete old cached files](http://docs.aws.amazon.com/AmazonS3/latest/UG/lifecycle-configuration-bucket-no-versioning.html) and not worry about it :)

Note that as per contribution guidelines usage questions should be asked on the Google group, and GitHub issues should only be used for reporting bugs.

**Comment by mkcode** [comment]
Thank you for the very thorough answer. I actually missed that the moving plugin existed, and was intending on writing one if it had not. Glad it does. It is impressive how well thought out this software is!  :+1:
