### ISSUE TITLE
Certain characters break 

### ISSUE THREAD

**Issue by mkcode** [janko-m/shrine#38]
Hello again @janko-m, I found a quick bug with processing:

If direct to s3 uploads contain that special `${filename}` part in the key, the `Down` library does not properly escape them.

The following error occurs when processing:

> Down::NotFound Message: bad URI(is not URI?): https://.../uploads/b969e2dba64b40c3884075bf611a5950cde2f190da1762b38f8222e52693/IMG_20150915_200027[1].jpg?X-Amz-Algorithm=...

Error backtrace:
> vendor/bundle/ruby/2.2.0/gems/down-1.1.0/lib/down.rb:47 in rescue in download
vendor/bundle/ruby/2.2.0/gems/down-1.1.0/lib/down.rb:14 in download
vendor/bundle/ruby/2.2.0/gems/shrine-1.2.0/lib/shrine/storage/s3.rb:130 in download
vendor/bundle/ruby/2.2.0/gems/shrine-1.2.0/lib/shrine.rb:742 in download
app/uploaders/attachment_uploader.rb:20 in process
vendor/bundle/ruby/2.2.0/gems/shrine-1.2.0/lib/shrine.rb:349 in processed

Now the `url` method produces the following url for the same resource, which works:

> https://.../uploads/b969e2dba64b40c3884075bf611a5950cde2f190da1762b38f8222e52693/IMG_20150915_200027%5B1%5D.jpg?X-Amz-Algorithm=...

Notice that the `[1]` part of the filename is is escaped `%5B1%5D` in the `url` version, and not escaped in the `down` version. 

This page contains character escaping info: http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html

-----

Also, note that this happened because I generated the `presigned_post` myself and did not use the `direct_upload` plugin. Perhaps you may not want to support using the `${filename}` syntax on the s3 key, which is fine in my opinion. I am fixing this in my application by removing the  `${filename}` part.

**Comment by janko-m** [comment]
I see, from testing it seems that `URI.encode` doesn't escape the `[]` characters for some reason. What Down does is `URI.encode(URI.decode(url))` so that you can pass both encoded and not encoded URLs (taken from https://github.com/carrierwaveuploader/carrierwave/issues/317).
To give an example, if you pass an unencoded URL, let's say with a space inside, `URI.parse` will not consider it a valid URL, so we `URI.escape` it. Likewise, if you pass an encoded URL (with "%" symbols inside), `URI.escape` would double-encode it, so we first need to `URI.decode` it.

However, it seems like `URI.encode` and `URI.decode` are not inverse functions. Furthermore, I found out now that both of these methods are deprecated, without a valid alternative. [Here](http://ruby-core.ruby-lang.narkive.com/0XKxdn7l/ruby-core-29293-uri-un-escape-deprecated) is a discussion about that (as I see the starting discussion is in japanese), but none of the mentioned alternatives have the same behaviour. However, `URI.escape("http://example.com/#foo")` produces `http://example.com/%23foo`, so `URI.escape` definitely has to go.

I think the proper solution is to make Down not do any unescaping-escaping, and require a properly encoded URL. I did this originally because it's done in CarrierWave (https://github.com/carrierwaveuploader/carrierwave/pull/115, https://github.com/carrierwaveuploader/carrierwave/pull/320, and recent one is https://github.com/carrierwaveuploader/carrierwave/pull/1013). But when I think about it now I don't know why it was encoded in the first place, because I cannot imagine from where can the user copy-paste an unencoded URL (AFAIK browsers always escape them).

Escaping "square brackets" directly wouldn't solve all problems, because there is still the `#` problem. So I think removing unescaping-escaping is the way to go, I'm just not sure if that could break someone's code

**Comment by janko-m** [comment]
I bumped the major version of Down, to signalize a potentially backwards incompatible change. But in normal situations where people are copy-pasting URLs from the browser it should never happen, because the browser always encodes URLs.

**Comment by mkcode** [comment]
Thanks for fixing this so quickly!
