### ISSUE TITLE
Breaking change on master

### ISSUE THREAD

**Issue by hakunin** [janko-m/shrine#39]
This used to work
```
    @upload = Upload.create!(resource_params)
```

With attributes passed being

```
{
 #...
 "attachment"=>
  {"id"=>
    "2162ef5ccc922cf071e81504c5cf08e60d135e7144887cb0565eb85ba021/Screen Shot 2016-01-25 at 15.16.39.png",
   "storage"=>"cache",
   "metadata"=>
    {"width"=>342,
     "height"=>348,
     "size"=>73681,
     "filename"=>"Screen Shot 2016-01-25 at 15.16.39.png",
     "mime_type"=>"image/png"}},
 }
```

Now I get 
```
Shrine::Error: unknown version: "id"`
from: /Users/michal/.rvm/gems/ruby-2.2.1/bundler/gems/shrine-01f20b64ef4a/lib/shrine/plugins/versions.rb" line 105 in block in versions!
```

If I go back to earlier revision `3ab14cb1ad71e1254b025bf4ae721c3fed52a16f` the code works.

**Comment by janko-m** [comment]
Yes, this was actually one of the documented breaking changes that version 1.0.0 introduced (the mentioned commit was prior to version 1.0.0). Prior to that version, cached files could be accepted as a hash or a JSON string. However, I didn't consider that essential functionality, and it was introducing problems when I was trying to write a plugin for multiple file uploads, so I extracted it out into a plugin for easier maintenance.

To get the old behaviour, just do `Shrine.plugin :parsed_json` in your initializer. Alternatively you could just send the cached file data as a JSON string instead of a hash.

**Comment by hakunin** [comment]
Thanks!
