### ISSUE TITLE
Is the `parsed_json?` string-keys check necessary?

### ISSUE THREAD

**Issue by reidab** [janko-m/shrine#42]
I'm using Shrine with a framework that automatically parses JSON query params, so the `parsed_json` plugin looked like a good fit. However, since the framework presents the parsed JSON with symbol string, [this check](https://github.com/janko-m/shrine/blob/master/lib/shrine/plugins/parsed_json.rb#L21) requiring String keys fails.

Is this check really necessary, or is there a particular edge case that it's trying to avoid?

Another option — Looking a bit deeper in the call path for `assign`: `assign_cached` calls `uploaded_file`, which accepts Hash arguments. Is the `Hash -> JSON String -> Hash` round trip that `parsed_json` offers worth it, or can `AttacherMethods#assign` just handle Hashes with the same code path used for Strings?

**Comment by janko-m** [comment]
The reason why Shrine is checking only for string keys is because there is another type of hash that can be assigned – the Rack uploaded file hash, enabled by the [rack_file](http://shrinerb.com/rdoc/classes/Shrine/Plugins/RackFile.html) plugin. If the parsed_json plugin would accept symbol keys, it would have to include a special case to check if it isn't the Rack uploaded file hash.

But the main reason why I don't think parsed_json should accept hashes with symbol keys is because that strictly isn't parsed JSON (symbols don't exist in JSON specification). Firstly, I think frameworks shouldn't automatically parse JSON strings, because it changes the type of parameter that is sent (it converts a string value into a hash). Putting that aside, I think it's bad that the keys are symbolized, mostly because it locks the Ruby version to 2.2 or higher, which introduce Symbol GC. I would rather that the framework provides an option to disable symbolizing keys.

In version 0.9 parsed_json plugin was actually part of base functionality. However, when I tried to implement a plugin for accepting multiple files, I've found that it creates a lot of edge cases. And since I didn't consider it essential functionality, I extracted it into a separate plugin so that it can be managed better. Although parsed_json does bring the round trip you've mentioned, and I currently don't consider the multiple files plugin worthwhile, I would still like to leave the path open.

**Comment by janko-m** [comment]
Also, as per contribution guidelines, it would be great if we could have discussions on the google group, and use GitHub issues only for bugs. I know that GitHub's markdown is much nicer to use, but I like having bugs and discussions separated, since I saw it work very well in Jeremy Evans' projects.
