### ISSUE TITLE
Mongoid Support?

### ISSUE THREAD

**Issue by nitinstp23** [janko-m/shrine#44]
Hey,

Does `shrine` supports `mongoid` as an ORM.

If not, would you consider a PR?

**Comment by janko-m** [comment]
Shrine doesn't support Mongoid at the moment. It is still on my TODO list, but since I'm not using MongoDB I never got to it. It would be great to have Mongoid integration, though I would prefer if it was a separate gem, just because I think MongoDB generally isn't as essential as SQL databases, but mostly because it's better that it's maintained by a person who uses it :smiley:. If you decide to create it, let me know so that I can link to it on the website (or send me a PR).

**Comment by nitinstp23** [comment]
Cool :+1:
