### ISSUE TITLE
Validation failed: Attachment file was not found or was too large, Attachment file was not found or was too large

### ISSUE THREAD

**Issue by hakunin** [janko-m/shrine#45]
Would it be possible to change this unhelpful message to say either
```
Validation failed: Attachment file was too large (XY)
```
or 
```
Validation failed: Attachment file was not found.
```
?

**Comment by hakunin** [comment]
Its not very nice that the download errors from RemoteUrl plugin are thrown away. Thats makes it hard to debug stuff:
https://github.com/janko-m/shrine/blob/89b8edf9836d66560e5661b564db670d36dc6863/lib/shrine/plugins/remote_url.rb#L120

**Comment by janko-m** [comment]
To your first question, yeah, it would probably be good to separate those two.

To your second question, I agree that it's not ideal. The reason why errors are thrown away is because from the user's perspective the download failed, and it's not relevant to the user to know in which way (unless there is a bug which doesn't allow valid URLs, like there was in Down versions prior to 2.0.0). If an error is raised, I thought it would be annoying to have to rescue it manually (and it's easy to forget).

What would you suggest to make it more debuggable? I was thinking that instead of passing the `url` to the `:error_message` block, it would be great to pass the error (a `Down::Error` instance). In that case it would also be good to add `#url` to `Down::Error`, so that you can know which URL failed.

**Comment by janko-m** [comment]
The reason why I didn't bump the Down version to 2.0.0 in Shrine is because it contained a potentially backwards incompatible change where unencoded URLs don't work anymore (that's why the major version bump). So I didn't want a minor version of Shrine to backwards incompatible. But on the other hand the bug that it fixes is pretty important, and it's highly unlikely that a user will ever copy-paste an unencoded URL (browsers always encode the links), so I think actually the Down bump would be justified.

**Comment by janko-m** [comment]
The master now has:

* Down bumped to 2.0.0 ([commit](https://github.com/janko-m/shrine/commit/002d340c78a3a918a0e6128d5fcb6151b818a0ca))
* Different error messages when file wasn't found and when it's too large ([commit](https://github.com/janko-m/shrine/commit/c623127bdc79f87d7299ef5f7386f9e22fc81d91))
* Ability to obtain the error instance when generating the error message ([commit](https://github.com/janko-m/shrine/commit/dd11caf1e6193848a0af71fb48ef36e4e6867ba0))

Thank you for your input!
