### ISSUE TITLE
Rails 3

### ISSUE THREAD

**Issue by dcalixto** [janko-m/shrine#5]
i used on rails 4 and worked very well, but on rails 3 when i upload file shows:

#<ActionDispatch::Http::UploadedFile:0x007fd93b01baf0 @original_filename="dededee.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"user[avatar]\"; filename=\"dededee.png\"\r\nContent-Type: image/png\r\n", @tempfile=#<Tempfile:/var/folders/4p/79mlwbyd6830qsq2x30wtspm0000gn/T/RackMultipart20151105-5296-1bybw4o>> is not a valid IO object (it doesn't respond to `eof?()`, `close()`)

so, is not compatible with rails 3?

**Comment by janko-m** [comment]
Yes, it's unfortunately not compatible, because `ActionDispatch::Http::UploadedFile` doesn't have those two methods in Rails 3. It would be great if Rails 3 wasn't end-of-life, so that we can submit a PR. I decided that inside of Shrine I don't want to do monkey patches for Rails 3.

You can put [this code](https://github.com/refile/refile/blob/master/lib/refile/rails.rb#L41-L54) in your Rails app to make it compatible. Alternatively it would be great if someone made a "shrine-rails" gem which contains this monkey patch.

**Comment by abepetrillo** [comment]
Just in case anybody else hits this page. I'm planning on writing the suggested shrine-rails gem. This would be part of a migration away from paperclip and upgrading from rails 3 to 4.

**Comment by abepetrillo** [comment]
https://github.com/abepetrillo/shrine-rails
