### ISSUE TITLE
Shrine ignores ActiveRecord's validate flag

### ISSUE THREAD

**Issue by martinsefcik** [janko-m/shrine#55]
When saving object using [resource.save(validate: false)](http://api.rubyonrails.org/classes/ActiveRecord/Validations.html#method-i-save) shrine still try to validate attachment and RecordInvalid exception is thrown with validation errors on attachment or on other resource fields if any exists.

**Comment by janko-m** [comment]
Shrine runs validations on attachment assignment, so they are run regardless of whether the record is validated or not. That's an intentional design decision, one reason being that it's consistent with plugins like remote_url and data_uri, where file assignment itself can fail and the errors need to be added at that moment.

However, Shrine errors are copied over to record's errors in a `validate` block, which is run only if the record is being validated. I can't reproduce your error, because exactly what I described happens:

```rb
require "active_record"
require "shrine"
require "shrine/storage/file_system"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Migration.verbose = false
ActiveRecord::Migration.create_table(:documents) { |t| t.text :file_data }

Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new("uploads/cache"),
  store: Shrine::Storage::FileSystem.new("uploads/store"),
}

Shrine.plugin :activerecord
Shrine.plugin :validation_helpers

class FileUploader < Shrine
  Attacher.validate do
    validate_min_size 10*1024*1024
  end
end

class Document < ActiveRecord::Base
  include FileUploader[:file]
end

document = Document.new(file: File.open(__FILE__))
document.save(validate: false)

p document.file_attacher.errors
p document.persisted?
```

**Comment by martinsefcik** [comment]
OK, it makes sense that attachment has to be always validated.

But is the following correct behavior ?
Case 1 (no attachment): document is persisted even it contains validation error (validate = false works)
```ruby
require "active_record"
require "shrine"
require "shrine/storage/file_system"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Migration.verbose = false
ActiveRecord::Migration.create_table(:documents) { |t|
  # t.text :file_data
  t.text :desc
}

Shrine.storages = {
    cache: Shrine::Storage::FileSystem.new("uploads/cache"),
    store: Shrine::Storage::FileSystem.new("uploads/store"),
}

Shrine.plugin :activerecord
Shrine.plugin :validation_helpers

class FileUploader < Shrine
  Attacher.validate do
    validate_max_size 10*1024*1024
  end
end

class Document < ActiveRecord::Base
  # include FileUploader[:file]

  validates :desc, presence: true
end

document = Document.new()
# document.file = File.open(__FILE__)
document.desc = nil # invalid value
document.save(validate: false)

# p document.file_attacher.errors
p document.persisted?
```

Case 2 (with attachment): document is NOT persisted, it is not valid again because desc is nil but file is valid (validate = false does not work)
```ruby
require "active_record"
require "shrine"
require "shrine/storage/file_system"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Migration.verbose = false
ActiveRecord::Migration.create_table(:documents) { |t|
  t.text :file_data
  t.text :desc
}

Shrine.storages = {
    cache: Shrine::Storage::FileSystem.new("uploads/cache"),
    store: Shrine::Storage::FileSystem.new("uploads/store"),
}

Shrine.plugin :activerecord
Shrine.plugin :validation_helpers

class FileUploader < Shrine
  Attacher.validate do
    validate_max_size 10*1024*1024
  end
end

class Document < ActiveRecord::Base
  include FileUploader[:file]

  validates :desc, presence: true
end

document = Document.new()
document.file = File.open(__FILE__)
document.desc = nil # invalid value
document.save(validate: false)

p document.file_attacher.errors
p document.persisted?
```

Maybe I'm wrong.

**Comment by janko-m** [comment]
Hmm, I'm not sure what do you mean. Can you explain me what is your expected behaviour of Shrine, and how does it differ from the current behaviour?

**Comment by janko-m** [comment]
To answer your question, both of your cases have correct behaviour to me. In both cases the records are persisted as expected, because validations are ignored.

**Comment by martinsefcik** [comment]
To make it clear.

Case 1 output is:
```ruby
true # persisted?
```

Case 2 output is:
```ruby
[]
false # persisted?
```
Yes, you are right it is persisted in both cases. _persisted?_ result confused me, because it is false, but why it is false if it was persisted ?
And why attachment is only in cache storage? I would expect it in store, or is it wrong expectation ?

**Comment by janko-m** [comment]
Ok, now I figured it out. I was getting `persisted?` returning true in both cases, without any errors (that's why I was confused), and realized now that this is because I was accidentally using the master branch of Shrine instead of the latest version.

The reason why this is happening is because Shrine saves the record twice, once with the cached version, and then it has an `after_commit` callback when it saves the record again, using `record.save!`. So that answers both questions, why is the record failing to save (because it doesn't pass `validate: false`) and why is it raising an error (because `save!` is used instead of `save`).

It seems that I have unknowingly fixed this in master in https://github.com/janko-m/shrine/commit/5d7cab67b65807ecbb56e5552871ffed5da34726, so you can pull from master. I will add additional tests for this case so that it doesn't happen again.

**Comment by martinsefcik** [comment]
Thanks a lot for explanation. It makes sense to me now. 
I will test it with master branch later today.

Do you have any estimates when a new version will be released ?

**Comment by janko-m** [comment]
I try to keep a monthly release of Shrine, so every month I just release what's currently on master. I see that working really great in Sequel and Roda, so I adopted it in Shrine as well. Since the last version was released on 12th of March, you can expect the next release on 12th of April.

**Comment by martinsefcik** [comment]
OK, thanks.
