### ISSUE TITLE
How to proxy caching images [:store, :cache] using nginx with docker?

### ISSUE THREAD

**Issue by ricardopacheco** [janko-m/shrine#59]
Here i run two containers: one for the application (with puma), and another with nginx. As used carrierware, i managed to get the pictures they were footprints by nginx for proxy caching, but shrine can not do.

Could someone send me a suggestion Dockerfile or docker-compose.yml making this option?

**Comment by janko-m** [comment]
Since Nginx proxies any requests to your application, your images should be normally cacheable if you're using the FileSystem storage (then file URLs go through the application), given that you have Nginx set up for caching. I think you can also simply configure the Rack::Static middleware (in Rails it's Rails::Static) to set the Cache-Control header to always cache the directory with uploaded files, and then you might not need to do additional configuration on Nginx. What exactly can you do with CarrierWave that you didn't manage to do with Shrine?

Since I prefer using the [Shrine Google group](https://groups.google.com/forum/#!forum/ruby-shrine) for answering usage questions, I will close the issue, but you can open a topic about this on the Google group.
