### ISSUE TITLE
Multiple Image Upload and preview?

### ISSUE THREAD

**Issue by Innarticles** [janko-m/shrine#60]
I feel like I would this gem. Does it support multiple image uploads and and immediate preview of the images before actual uploads?

**Comment by janko-m** [comment]
Yes, it's possible to implement multiple image uploads with Shrine, it has a [direct_upload](http://shrinerb.com/rdoc/classes/Shrine/Plugins/DirectUpload.html) feature which you can use for that. The [Rails example app](https://github.com/erikdahlstrand/shrine-rails-example) (and [Roda version](https://github.com/janko-m/shrine-example)) demonstrate multiple image uploads directly to S3. The only thing missing are image previews, but you can easily add them in JavaScript (image previews can always be done with JavaScript regardless of what you're using on the server).

Note that usage questions are best asked on the [Shrine Google group](https://groups.google.com/forum/#!forum/ruby-shrine), so that GitHub issues are used only for bug reports or PR.
