### ISSUE TITLE
sending data to model instances

### ISSUE THREAD

**Issue by calebbourg** [janko-m/shrine#64]
hey Janko-m,

Sorry to bother you again. I have another question about Shrine. 
The code that you graciously gave to me is working very well. 
I’m confused about how the included plugin is working. When I go to save
an instance of my model(in this case track) through it’s controllers’ #create action. 
is there a way that shrine can know that the uploaded file is associated with the Track instance being saved?

here is the code again

```rb
class AudioUploader < Shrine
  MAX_FILESIZE = 50.megabytes

  MIME_TYPES = %w(audio/mpeg audio/mp3 audio/ogg audio/x-aiff audio/flac  application/octetstream).freeze # validate type
  IS_LOCAL = Rails.env.test? || Rails.env.development? && ENV.key?('LOCAL_UPLOADS')
  plugin :direct_upload, max_size: MAX_FILESIZE, presign: !IS_LOCAL
  plugin :remote_url,    max_size: MAX_FILESIZE
  plugin :hooks

  plugin :included do |name|
    before_save do
      if send("#{name}_data_changed?") && send(name) && send(name).storage_key == "cache"
        self.waveform = send(name).metadata["peaks"]
      end
    end
  end

  def around_upload(io, context)
    @super_audio = super
    if context[:phase] == :cache
      if io.respond_to?(:tempfile)

        audio = FFMPEG::Movie.new(io.tempfile.path)
        wav = Tempfile.new(['forwaveform', '.wav'])
        audio.transcode(wav.path)
        length = 60
        info = WaveFile::Reader.info(wav.path)
        sample_size = info.sample_frame_count / length
        peaks = []
        WaveFile::Reader.new(wav.path, WaveFile::Format.new(:mono, :float, 44_100)) do |reader|

          reader.each_buffer(sample_size) do |buffer|
            intermediary = []
            steps = buffer.samples.length / 10
            (0..9).each do |step|
              intermediary.push(buffer.samples[step * steps].round(2))
            end

            peaks.push(intermediary.max)
            peaks.push(intermediary.min)
          end

          @super_audio.metadata.update("peaks" => peaks)
        end
      end
    end
  end
end
```

the upload happens first and then afterward a form is filled out the track is created.

thank you so much 
please let me know if you need more information

**Comment by janko-m** [comment]
The only thing that included plugin does is allow you to define additional things on the model when including the attachment module. It exists because it's nicer to have all upload logic managed from the uploader class, otherwise there is no difference between calling `before_save` in the model directly.

I'm not sure I understand the question. From the `Shrine::UploadedFile` instance itself you cannot find out to which model it belongs to, because it is agnostic to how it is saved. But I don't understand in which part of the code you would like to have access to the model instance (Track). Is it that you would like direct uploads to behave differently than when audio is uploaded for a Track vs some other model?

Let's just continue this discussion on the [Shrine Google group](https://groups.google.com/forum/#!forum/ruby-shrine), as I prefer to use GitHub issues only for bugs and PRs.
