### ISSUE TITLE
Is this possible to do progress-bar based on synchronous file upload?

### ISSUE THREAD

**Issue by AlexShmatko** [janko-m/shrine#70]

**Comment by janko-m** [comment]
Could you explain in more detail what do you mean? Do you mean like a server-side progress bar in the promote phase?

**Comment by janko-m** [comment]
So, as I understood, you would like to have a client-side progress when uploading, but with using `remote: true`. Unfortunately, this isn't possible, because the progress bar is only applicable to uploading itself, once you're in your controller the uploading is already finished. If you want a progress bar, you need to use a JS library like jQuery-File-Upload or Dropzone.js instead of `remote: true`, along with the [direct_upload](http://shrinerb.com/rdoc/classes/Shrine/Plugins/DirectUpload.html) plugin.

I will close this as I prefer using GitHub issues only for bug reports, but if you have any more questions or want to continue the discussion, a much better place to do that is on the [Shrine Google group](https://groups.google.com/forum/#!forum/ruby-shrine).
