### ISSUE TITLE
How best to include images with fixtures?

### ISSUE THREAD

**Issue by pmackay** [janko-m/shrine#82]
I'm using shrine (great gem!) and also fixtures for tests and sample seed data. [This](http://jeffkreeftmeijer.com/2014/using-test-fixtures-with-carrierwave/) is a set of handy tips how to use images with CarrierWave, are there any similar docs for including images with some test fixtures when working with Shrine?

**Comment by janko-m** [comment]
To achieve a similar setup with Shrine using the filesystem storage, you can upload the file to the storage in `setup`, and clear the storage in `teardown`. Then you can assign the uploaded file to the `<attachment>_data` column in the fixture.

```rb
# test/test_helper.rb
class ActiveSupport::TestCase
  setup do
    image = File.open("test/fixtures/files/tapir.jpg")
    Shrine.storages[:store].upload(image, "tapir.jpg")
  end

  teardown do
    Shrine.storages.values.each(&:clear!)
  end
end
```
```yml
# test/fixtures/users.yml
user_with_avatar:
  avatar_data: '{"id":"tapir.jpg","storage":"store","metadata":{"filename":"tapir.jpg","mime_type":"image/jpeg","size":98423}}'
```

With Shrine you can also use [shrine-memory](https://github.com/janko-m/shrine-memory) storage, so that you don't have to worry about cleaning the directory (and it's also faster than writing to disk).

```rb
# Gemfile
gem "shrine-memory"
```
```rb
# test/test_helper.rb
require "shrine/storage/memory"

Shrine.storages = {
  cache: Shrine::Storage::Memory.new,
  store: Shrine::Storage::Memory.new,
}

class ActiveSupport::TestCase
  setup do
    image = File.open("test/fixtures/files/tapir.jpg")
    Shrine.storages[:store].upload(image, "tapir.jpg")
  end
end
```

Note that usage questions are best asked on the [Shrine google group](https://groups.google.com/forum/#!forum/ruby-shrine), I prefer to use GitHub issues only for bug reports 😉

**Comment by janko-m** [comment]
To follow-up here as well, I realized that probably the easiest way to attach files in fixtures is using data URIs, I explained it [here](http://shrinerb.com/rdoc/files/doc/testing_md.html#label-Test+data).

**Comment by pmackay** [comment]
Massive thanks for this info @janko-m, much appreciated!

**Comment by janko-m** [comment]
@pmackay Unfortunately, this strategy doesn't work, because Rails fixtures seem to require that all key-value pairs are actual columns, it won't accept virtual attributes (like `<attachment>_data_uri`). See https://github.com/janko-m/shrine/issues/117 for a discussion about this.

With this limitation I didn't see any correct way to setup attachment with Rails fixtures, so I removed the "fixtures" section from the "Testing Shrine" guide.
