### ISSUE TITLE
How does shrine works with non-image files?

### ISSUE THREAD

**Issue by hakunin** [janko-m/shrine#9]
Hi, I haven't found much info on non image files.

I am going to use pre-signed s3 urls so there is no way I can tell upfront if the file is image or not and I want all kids of files uploaded.

Hopefully shrine will work in my case, is there anything to keep in mind in this use-case?

**Comment by janko-m** [comment]
Yes, Shrine works with any types of files, the README just demonstrates images because they're the most common types of files. The base functionality of Shrine doesn't have any image-specific logic, it just treats all files the same (just some plugins and processing add image-specific functionality, but naturally you just won't load those when you're handling all types of files).

Note that as per contribution guidelines it would be great if you ask questions on the google group, and use GitHub issues only for bugs or pull requests. Thanks!
