### ISSUE TITLE
how to integrate Ckeditor gem?

### ISSUE THREAD

**Issue by 1989medium** [janko-m/shrine#90]

**Comment by janko-m** [comment]
You can configure CKEditor to upload the file to Shrine's [direct upload](http://shrinerb.com/rdoc/classes/Shrine/Plugins/DirectUpload.html) endpoint, and then after upload assign the value in the response body to a hidden field which will get submitted when the CKEditor form is submitted, and then you set up attaching the uploaded file to a model just like in the README. I cannot point you to specifics since I'm not familiar with CKEditor, but I don't think it should be difficult.

Note that as per contribution guidelines, usage questions should be asked on the [Shrine google group](groups.google.com/forum/#!forum/ruby-shrine), GitHub issues should only be used for bug reports.
