### ISSUE TITLE
Get the :store url even when a cache exists

### ISSUE THREAD

**Issue by kernow** [janko-m/shrine#96]
Hi,

I'm trying to convert our project from carrierwave to shrine and I'm wondering the best way to achieve the functionality of our company logo upload. We have a page that displays a companies existing logo and has a form to replace the logo. Logos must be an image file. If the company has an existing logo and I try to upload a non-image file a validation error is shown as expected. However the existing company logo that is displayed on the page is trying to display the `:cache` non-image file that failed to validate.

The behaviour I want is to aways display the `:store` logo (the one the DB record points to) even when a new file is uploaded that fails validation. The behaviour I have when using `image_tag @company.logo_url(:thumbnail)` is that the `:cache` version is used when a new file is uploaded.

I can get the `:store` information using `@company.logo_attacher.store` but I can't see any methods to generate the url from this object. Is there a way to always retrieve the url for the `:store` version of the image rather than having the `:cache` version take precedence?

FYI, I'm using the `versions` plugin.

**Comment by janko-m** [comment]
@kernow You are correct, the cached file will overwrite the previous attachment in case of validations, making the previous attachment not easily accessible (only through manual conversion from ActiveRecord's `<column>_was` dirty tracking attribute).

My first thought was that you can use the `remove_invalid` plugin, but now I see that it will always deassign the invalid cached file and assign `nil` instead, instead of assigning back the previous attachment. I think the latter is the expected behaviour. I will fix that shortly.

**Comment by kernow** [comment]
@janko-m thanks, I had though about using dirty attributes but thought I'd ask you first in case there was an easier way to do it. Maybe having the `logo_url` method accept options that can specify which storage you want the url for would be an easy way to do this, e.g.

`@company.logo_url(:thumbnail, store: :store)`
`@company.logo_url(:thumbnail, store: :cache)`

or something like that, alternatively something like this style would be good also

`@company.logo.store.url(:thumbnail)`
`@company.logo.cache.url(:thumbnail)`

**Comment by janko-m** [comment]
@kernow This wouldn't really be possible, because Shrine only has a notion of "previous" attachment, so it wouldn't make sense to specify a particular storage if it only has one previous attachment.

But when I push a fix for the `remove_invalid` plugin, you should be able to use it for your use case (and won't need to make any conditionals). The only thing is that you won't be able to access the invalid `:cache` file (other than via dirty attributes), but as I understood you don't need it, right?

**Comment by kernow** [comment]
@janko-m I understand, yes that would be fine, I don't need access to any invalid files. Thanks

**Comment by kernow** [comment]
@janko-m thanks for the fast release, working great now 👍
