### ISSUE TITLE
Validation plugin not executed on direct uploads

### ISSUE THREAD

**Issue by andredurao** [janko-m/shrine#98]
I'm following the documentation and [rails example](https://github.com/andredurao/shrine-rails-example/blob/master/app/models/image_uploader.rb) but I could not validate MimeTypes and neither file sizes on Shrine using direct uploads:

This is my uploder:

```ruby
require "image_processing/mini_magick"

class ImageUploader < Shrine

  plugin :determine_mime_type
  plugin :remove_attachment
  plugin :store_dimensions
  plugin :validation_helpers
  plugin :pretty_location

  plugin :direct_upload, presign_options: ->(request) do
    filename = request.params["filename"].inspect
    {
      content_disposition: "attachment; filename=#{filename}" # download with original filename
    }
  end

  Attacher.validate do
    validate_mime_type_inclusion %w[image/jpeg image/png image/gif]
    validate_max_size 500.kilobytes
  end

end

```

Do I need to create a validation on the model like this for presigned uploads?
```ruby
#...
  validate  :mime_type_validation
  def mime_type_validation
    unless %w[image/jpeg image/png image/gif].include?(file.mime_type)
      errors.add(:file, :invalid)
    end
  end
#...
```

What may be causing this "ignore" on validations?

_Originally I wasn't adding ""image_processing/mini_magick" because I'm not reprocessing the files uploaded,  I added to verify if shrine needs that to validate but even after the validation was not called._
_Ruby 2.3.0 / Rails 4.2.7 / Shrine 2.3.1_

**Comment by hyperionel** [comment]
I've struggled with this issue for the last couple of days and what I found I was missing was the RestoreCachedData plugin.
https://github.com/janko-m/shrine/blob/master/lib/shrine/plugins/restore_cached_data.rb

This re-extracts the meta-data from the cached file before the validation so the determine_mime_type plugin can actually kick in and verify the mime type. Otherwise it would just use the metadata you pass to him.

My issue was that some users were trying to upload files with modified extensions and the validations were not working.
I might be wrong in your case but adding that plugin fixed it for me.

Either way it would be nice if this was in the documentation.

**Comment by andredurao** [comment]
Thanks @hyperionel, but that didn't worked.

I even tried the same gem versions on (https://github.com/erikdahlstrand/shrine-rails-example)

I'm checking the Rails example application and took out a few items that were not relevant to me and the uploader now is just this, but I use the same on my app it doesn't work like on example app:
```ruby
class ImageUploader < Shrine
  plugin :determine_mime_type
  plugin :remove_attachment
  plugin :validation_helpers
  plugin :pretty_location

  Attacher.validate do
    validate_max_size 500.kilobytes, message: 'is too large (max is 500 KB)'
    validate_mime_type_inclusion ['image/jpeg', 'image/png', 'image/gif']
  end
end
```

```ruby
#config/initializers/shrine.rb
require "shrine"
require "shrine/storage/s3"

s3_options = {
  access_key_id:     ENV.fetch("S3_ACCESS_KEY_ID"),
  secret_access_key: ENV.fetch("S3_SECRET_ACCESS_KEY"),
  region:            ENV.fetch("S3_REGION"),
  bucket:            ENV.fetch("S3_BUCKET"),
}

Shrine.storages = {
  cache: Shrine::Storage::S3.new(prefix: "cache", **s3_options),
  store: Shrine::Storage::S3.new(prefix: "store", **s3_options),
}

Shrine.plugin :activerecord
Shrine.plugin :logging, logger: Rails.logger
Shrine.plugin :direct_upload, presign: true

```

**Comment by andredurao** [comment]
The problem was much simpler... 😭

The javascript was sending a JSON with `file_data` instead of just `file`

That caused the problem and skipped the validation and other plugins to be executed, the files were also not being moved to `store` they kept on `cache` folder.

The file json was:

```json
"file_data":{
    "id":"6bf27b053f5c0bfad0596cb379e13189.txt",
    "storage":"cache",
    "metadata":{
      "size":5,
      "filename":"test.txt",
      "mime_type":"text/plain"
    }
  }
```

When it should be:

```json
"file":{
    "id":"6bf27b053f5c0bfad0596cb379e13189.txt",
    "storage":"cache",
    "metadata":{
      "size":5,
      "filename":"test.txt",
      "mime_type":"text/plain"
    }
  }
```

**Comment by janko-m** [comment]
@andredurao Glad you figured it out! Yeah, the assignment needs to go via the Shrine attribute, otherwise Shrine won't trigger its functionality.

@hyperionel The `restore_cached_data` plugin is mentioned in the [Direct Uploads to S3](http://shrinerb.com/rdoc/files/doc/direct_s3_md.html#label-Metadata) guide.

**Comment by hyperionel** [comment]
@janko-m My bad, I missed that. Love the gem. Thanks!

**Comment by aubreywahl** [comment]
I seem to be having the same problem under almost the exact same circumstances mentioned (running the example rails project, no validations are run). Do validations for direct uploads 
not work in rails?

**Comment by janko-m** [comment]
If you upload the file via direct upload, and submit the JSON as described in the documentation, the validations should be executed as if you were submitting a raw file to your Rails app.

There is nothing about Rails that would make file validations not run, as long as you have the activerecord plugin loaded.

**Comment by silent-e** [comment]
Does anyone have a good way to run the validations during the initial upload?  My use case is needing to run virus detection on directly uploaded files and any that fail should be deleted with a 422 response error and a helpful error message.

And despite my particular use case, why aren't validations run on initial upload? That would seem to be the best time to perform the validations.  Anything failing validation would be captured, as an error response, by the upstream JS library and with the `remove_invalid` plugin would be automatically deleted from the server.

I realize that a direct upload to s3 would greatly complicate running validations on first upload since you don't even have access to the file.

I'm currently attempting to write a Rack handler and passing that to the `upload_endpoint` plugin.  This handler would do the validations.

Or perhaps using the `processing` plugin to capture and preprocess in the :cache context?

**Comment by jrochkind** [comment]
@silent-e What is your exact use-case? Normally validations should be run when you try to save the model, same as other validations in Rails. (assuming you are using Rails). 

Direct uploads do complicate this, although validations should _still_ normally be run when you save the model, after assigning the data from the direct upload. 

So I'm not sure what's going on your situation, you may need to provide more details or code. 

For virus checking, the challenge I have run into is that virus checking may take non-trivial time (and require the entire file to be retrieved from remote storage, unlike some other metadata extraction that can be done with just some initial bytes).  Because the whole process is kind of slow, I don't actually want it to be done before model save, and before an HTTP response can be returned. So I want it to be done in the background. And prevent "promotion" of the file. But then feedback needs to be given to the user somehow. This all gets a bit complicated, and I haven't figured out a general-purpose solution yet. (I don't think any other file attachment libraries, including ActiveStorage, can handle this automatically either). 

But it really depends on what exactly you are doing, and what you want to do.  Normally validations will be run on model save, same as any other model attributes. I'm not sure exactly what you are doing or expecting or desiring. Hmm, you want to do a direct upload to your custom rack handler, have that rack handler run validations, and if they fail return some kind of response in an HTTP error message that your JS can handle?  You can probably make that happen, but will have to write code in your custom rack handler to do it. There's no way for shrine to automatically integrate with a custom rack handler that isn't written yet!

**Comment by silent-e** [comment]
Thanks for the quick reply. Apologies for the length of this reply.

I’m not using a remote upload location such as S3.  I’m accepting files onto the server so I have access to the actual files.  I’ve been able to write a simple service that does the virus scan. I use the `add_metadata` plug-in to add the result to the metadata passed to the Rack handler which responds with the correct rack response based on the scan result. True, the virus scan is taking about 11-15 seconds per file but, since each file is immediately uploaded, that time allows the user to continue updating the form. We are more interested in letting the user know about issues with each upload before submission.

I’m planning on creating some constants for the validation configs so I can use them in both the uploader and the rack response builder. I’m also considering looking at Shrine’s code on how to call its validators directly but that’ll be a future enhancement.

Since the rack response builder already receives some metadata via the file I can run my own bespoke validations.

I don’t have ready access to the docs at the moment but IIRC the metadata available in the rack builder is what was sent by the browser? I’m guessing I’ll have to do my own mine type detection.

I could imagine interest in a plugin that, given the caveat of not working on remote uploads, performing all validations and responding appropriately via Rack.

(e)

**Comment by janko-m** [comment]
> Does anyone have a good way to run the validations during the initial upload? My use case is needing to run virus detection on directly uploaded files and any that fail should be deleted with a 422 response error and a helpful error message.

You can configure the `upload_endpoint` plugin to do that:

```rb
plugin :upload_endpoint,
  upload: -> (io, context, request) {
    if VirusDetection.call(io) == false
      MyUploader.new(:cache).upload(io, context)
    end
  },
  rack_response: -> (uploaded_file, request) {
    if uploaded_file
      [200, { "Content-Type" => "application/json; charset=utf-8" }, [uploaded_file.to_json]]
    else
      [422, {}, ["File has viruses"]]
    end
  }
```

> And despite my particular use case, why aren't validations run on initial upload?

Because as you said, they won't work with direct uploads to a cloud storage like S3. In that case you'd need to think of another solution, so it makes sense for me to use that same solution for both scenarios.

Another reason is that validations are currently ran as part of the *attaching* phase, not the upload phase. That's because we want to merge the validation errors together with model validations. Also, the model instance is available during validations on attachment, which wouldn't be the case for direct uploads.

As @jrochkind said, it makes sense just to run virus detection outside of Shrine validations. And if you see the source code, you'll see that Shrine validations are just `record.attachment_attacher.errors << "validation error"`. 

> I don’t have ready access to the docs at the moment but IIRC the metadata available in the rack builder is what was sent by the browser? I’m guessing I’ll have to do my own mine type detection.

The `determine_mime_type` plugin exposes the `Shrine.determine_mime_type` method for extracting the MIME type, which uses the selected analyzer, so no need to implement your own MIME type detection 😉
