### ISSUE TITLE
Merging Options

### ISSUE THREAD

**Issue by jonasheinrich** [janko-m/shrine#99]
Hi Janko, 

I am using your `direct_upload` plugin with Rails and I have the following problem: All uploaders should set the `Content-Type` as in your example:
```
# initialiser
Shrine.plugin :direct_upload,
  presign_options: -> (request) {
  opts = { content_length_range: 0..2.megabytes }
  if filename = request.params["filename"]
    opts.merge!(content_disposition: "inline; filename=\"#{filename}\"")
  end
  opts
}
```

But one uploader has different file size limitations:
```
# class SpecificUploader
plugin :direct_upload, presign_options: { content_length_range: 0..50.megabytes }
```

Unfortunately, for the `SpecificUploader` the `Content-Disposition` from the general configuration gets overwritten. 

I think a good solution would be to merge options down the road (options from more specific classes take precedence). Maybe some kind of pipeline like it's used in the `processing` plugin. 

I would also try to implement it myself but I'm currently not sure what the best solution would be. Any recommendations?

Thanks, 

Jonas

**Comment by janko-m** [comment]
I'm not sure that merging options would be the ideal behaviour for plugin options. Foremost, that would mean that if a subclass needs to remove any options, it needs to override them with `nil` values explicitly. I think I prefer that plugin options whose values are hashes still work the same way as all other plugin options, that assigning them in a subclass overrides what was previously set.

For your case you could assign the maximum filesize into a constant in your uploader, and then reference it both in your file validations and general presign options. You can actually access the uploader class from presign options using the Roda `request` object:

```rb
request.scope # roda instance
request.scope.opts[:shrine_class] # uploader class
```

So then you could write something like this:

```rb
class SpecificUploader < Shrine
  MAX_SIZE = 50.megabytes
end
```
```rb
# initializer
Shrine.plugin :direct_upload,
  presign_options: -> (request) {
    uploader_class = request.scope.opts[:shrine_class]
    max_size = uploader_class::MAX_SIZE
    opts = { content_length_range: 0..MAX_SIZE }
    # ...
  }
```

I agree that it might not be ideal, maybe this could be improved somehow and/or documented.

Note that while you should definitely limit the maximum filesize for S3, it's probably enough to just use the lowest-common denominator, to take the largest allowed filesize from all uploaders and in your initializer use that as the limit (in your case that's 50MB). Because when JavaScript is enabled, you can have client-side filesize validations which already prevent the upload. And if an attacker disables JavaScript because they want upload large files to your S3 storage, they will likely be doing it on the records which allow 50MB limit anyway. But that's just my opinion, maybe there is a benefit that I'm not seeing.

**Comment by jonasheinrich** [comment]
Thanks for your response. I think I will go with the solution with constants since I like the clarity/explicitness.
